.TH REPARTITION 8
.SH NAME
repartition \- load a partition table
.SH SYNOPSIS
\fBrepartition\fP \fIdevice\fP [\fIpartition-file\fP]
.SH DESCRIPTION
.B Repartition
uploads a new partition table for the partitions of
.IR device .
The table is obtained from the first sector of
.I partition-file
if given,
.I device
otherwise.
.I Device
may refer to the whole drive or a primary partition, depending on whether you
want to upload a partition or a subpartition table.  The partitions will be
truncated to fit within the enclosing device like the disk driver does,
unless the numbers are coming from
.IR partition-file .
.SH EXAMPLES
repartition /dev/hd0
.br
repartition /dev/hd4 /etc/hd4.table
.PP
Reload the partition table of drive 0 setting /dev/hd[1\-4], and the
subpartition table of /dev/hd4 setting /dev/hd4[a\-d] using a file.
The latter may be useful if you need more than the 4 subpartitions a
single MINIX 3 partition gives you.
.SH DIAGNOSTICS
The new table is printed on standard output.
.SH FILES
/dev/hd[0-9]
.SH "SEE ALSO"
.BR hd (4),
.BR part (8).
.SH BUGS
The disk must be in use for the changes to stick.  The partition table of
an idle disk will be reloaded on the first open.
.SH AUTHOR
Kees J. Bot (kjb@cs.vu.nl)
