#	$NetBSD: Makefile,v 1.2 2012/06/17 07:40:25 joerg Exp $

HOST_BUILD=

.include "${.PARSEDIR}/../llvm/Makefile.inc"

.include "${LLVM_TOPLEVEL}/Makefile.inc"
.include "${LLVM_TOPLEVEL}/include/Makefile"
