#! /bin/sh

#
# $NetBSD: tzcode2netbsd,v 1.6 2015/07/11 16:09:15 christos Exp $
#
# Convert an extracted tzcode distribution into the format suitable
# for importing it into the NetBSD source tree.
# Last updated for: tzcode2004a.
# 

NOIMPORT="Makefile
	date.1 date.1.txt date.c
	gccdiffs
	itca.jpg
	logwtmp.c
	newctime.3.txt
	newstrftime.3 newstrftime.3.txt
	newtzset.3.txt
	time2posix.3.txt
	tzfile.5.txt
	tzselect.8.txt
	usno1988 usno1989 usno1989a usno1995 usno1997 usno1998
	zdump.8.txt
	zic.8.txt"

#rm -f ${NOIMPORT}
#mv tzfile.h ../../../include

echo remember to check tzfile.h in ../../../include
echo you can find the current version in the Makefile
echo we don't use this script anymore to import, but diff against the
echo current version and apply patches.
