#define _MINIX
#define _POSIX_SOURCE
#include <minix/callnr.h>
#include <minix/com.h>
#include <minix/config.h>
#include <minix/const.h>
#include <minix/endpoint.h>
#include <minix/ipc.h>
#include <minix/syslib.h>
#include <minix/sysutil.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
