# Makefile for lib/math.

CFLAGS	= -O -D_MINIX -D_POSIX_SOURCE

LIBRARIES = libc

libc_OBJECTS	= \
	asin.o \
	atan.o \
	atan2.o \
	ceil.o \
	exp.o \
	fabs.o \
	floor.o \
	fmod.o \
	hugeval.o \
	log.o \
	log10.o \
	pow.o \
	sin.o \
	sinh.o \
	sqrt.o \
	tan.o \
	tanh.o \

include ../Makefile.inc
