#	$NetBSD: Makefile.inc,v 1.6 2010/01/14 02:09:46 joerg Exp $

SRCS+=	byte_swap_2.S byte_swap_4.S byte_swap_8.S
SRCS+=	ffs.S
SRCS+=	memchr.S memcmp.S memcpy.S memmove.S memset.S
SRCS+=	strcat.S strchr.S strcmp.S
SRCS+=	strcpy.S strlen.S
SRCS+=	strrchr.S
SRCS+=	scanc.S skpc.S
SRCS+=	random.S
