# Makefile for lib/ack/i386/em.

CFLAGS	= -O -D_MINIX -D_POSIX_SOURCE -Was-ack

LIBRARIES = libe

libe_OBJECTS	= \
	em_adf4.o \
	em_adf8.o \
	em_adi.o \
	em_and.o \
	em_blm.o \
	em_cff4.o \
	em_cff8.o \
	em_cfi.o \
	em_cfu.o \
	em_cif4.o \
	em_cif8.o \
	em_cii.o \
	em_cmf4.o \
	em_cmf8.o \
	em_cms.o \
	em_com.o \
	em_csa4.o \
	em_csb4.o \
	em_cuf4.o \
	em_cuf8.o \
	em_cuu.o \
	em_dup.o \
	em_dvf4.o \
	em_dvf8.o \
	em_dvi.o \
	em_dvu.o \
	em_error.o \
	em_exg.o \
	em_fat.o \
	em_fef4.o \
	em_fef8.o \
	em_fif4.o \
	em_fif8.o \
	em_fp8087.o \
	em_gto.o \
	em_hol0.o \
	em_iaar.o \
	em_ilar.o \
	em_inn.o \
	em_ior.o \
	em_isar.o \
	em_lar4.o \
	em_loi.o \
	em_mlf4.o \
	em_mlf8.o \
	em_mli.o \
	em_mon.o \
	em_ngf4.o \
	em_ngf8.o \
	em_ngi.o \
	em_nop.o \
	em_print.o \
	em_rck.o \
	em_rmi.o \
	em_rmu.o \
	em_rol.o \
	em_ror.o \
	em_sar4.o \
	em_sbf4.o \
	em_sbf8.o \
	em_sbi.o \
	em_set.o \
	em_sli.o \
	em_sri.o \
	em_sti.o \
	em_stop.o \
	em_trp.o \
	em_unknown.o \
	em_xor.o \

include ../../../Makefile.ack.inc
