# 	$NetBSD: Makefile,v 1.17 2012/08/29 17:13:22 drochner Exp $

INCSDIR=/usr/include/x86

INCS=	aout_machdep.h \
	bootinfo.h \
	cacheinfo.h \
	cpu.h \
	cpu_ucode.h \
	cputypes.h \
	cpuvar.h \
	float.h \
	ieee.h ieeefp.h \
	intr.h intrdefs.h \
	lock.h \
	math.h mutex.h mtrr.h \
	pio.h \
	pmap.h \
	pmap_pv.h \
	psl.h \
	pte.h \
	rwlock.h \
	specialreg.h \
	sysarch.h \
	trap.h \
	via_padlock.h

.include <bsd.kinc.mk>
