# 	$NetBSD: Makefile,v 1.17 2012/08/29 17:13:22 drochner Exp $

INCSDIR=/usr/include/x86

INCS=	\
	bootinfo.h \
	cpu.h \
	float.h \
	ieee.h ieeefp.h \
	math.h mutex.h \
	pio.h \
	rwlock.h \


.include <bsd.kinc.mk>
