#	$NetBSD: Makefile,v 1.1 2011/10/11 13:54:01 joerg Exp $

HOSTPROGNAME=	${_TOOL_PREFIX}clang-tblgen
HOSTPROG_CXX=	${_TOOL_PREFIX}clang-tblgen
HOST_SRCDIR=	external/bsd/llvm/bin/clang-tblgen

.include "${.CURDIR}/../Makefile.host"
