
SUBDIR+=	include .WAIT
SUBDIR+=	benchmarks
SUBDIR+=	bin
SUBDIR+=	commands
SUBDIR+=	drivers
SUBDIR+=	fs
SUBDIR+=	kernel
SUBDIR+=	lib
SUBDIR+=	llvm
SUBDIR+=	man
SUBDIR+=	net
SUBDIR+=	sbin
SUBDIR+=	servers
SUBDIR+=	share
SUBDIR+=	tests
SUBDIR+=	usr.bin
SUBDIR+=	usr.sbin

.include <bsd.subdir.mk>
