.TH man 8 "13 November 2014" "1.0" "autopart man page"
.SH NAME
autopart \- Partition a hard disk for Minix installation

.SH SYNOPSIS
autopart

.SH DESCRIPTION
This tool is used as the third step in the install process. 
It is not intended for use as a partitioning tool
Use part(8) instead.

.SH EXAMPLES
autopart

.SH SEE ALSO
part(8)

.SH AUTHOR
Manpage written by Jacob Adams <tookmund@gmail.com>
