MAN=	configfile.5 crontab.5 dhcp.conf.5 dir.5 ethers.5 \
	fstab.5 hosts.5 httpd.conf.5 http_status.5 keymap.5 \
	passwd.5 resolv.conf.5 resolver.5 rhosts.5 serv.access.5 \
	syslog.conf.5 termcap.5 ttytab.5 TZ.5 tzfile.5 utmp.5 \
	whatis.5

.include <minix.man.mk>
.include <minix.subdir.mk>
