
INCSDIR= /usr/include/i386

INCS=	archconst.h archtypes.h bios.h cmos.h \
	diskparm.h elf.h fpu.h int86.h interrupt.h \
	ipcconst.h memory.h partition.h \
	pci_amd.h pci.h pci_intel.h pci_sis.h \
	pci_via.h ports.h stackframe.h vm.h

.include <bsd.kinc.mk>

