# Makefile for lib/i386/string.

LIBRARIES = libc

libc_OBJECTS	= \
	_memmove.o \
	_strncat.o \
	_strncmp.o \
	_strncpy.o \
	_strnlen.o \
	bcmp.o \
	bcopy.o \
	bzero.o \
	index.o \
	memchr.o \
	memcmp.o \
	memcpy.o \
	memmove.o \
	memset.o \
	rindex.o \
	strcat.o \
	strchr.o \
	strcmp.o \
	strcpy.o \
	strlen.o \
	strncat.o \
	strncmp.o \
	strncpy.o \
	strnlen.o \
	strrchr.o \

include ../../Makefile.inc
