.\" $NetBSD: cimag.3,v 1.4 2012/12/27 21:34:10 wiz Exp $
.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved
.Dd December 27, 2012
.Dt CIMAG 3
.Os
.Sh NAME
.Nm cimag ,
.Nm cimagf ,
.Nm cimagl
.Nd complex imaginary functions
.Sh SYNOPSIS
.In complex.h
.Ft double
.Fn cimag "double complex z"
.Ft float
.Fn cimagf "float complex z"
.Ft long double
.Fn cimagl "long double complex z"
.Sh DESCRIPTION
These functions compute the imaginary part of
.Ar z .
.Sh RETURN VALUES
These functions return the imaginary part value (as a real).
.Sh ERRORS
No errors are defined.
.Sh APPLICATION USAGE
For a variable
.Ar z
of complex type:
.Bd -literal -offset indent
z = creal(z) + cimag(z)*I
.Ed
.Sh SEE ALSO
.Xr carg 3 ,
.Xr conj 3 ,
.Xr cproj 3 ,
.Xr creal 3 ,
.St -p1003.1-2001
.Aq Pa complex.h
.Sh COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group.
In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document.
The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
