.\" $NetBSD: cpow.3,v 1.3 2013/01/29 02:05:09 matt Exp $
.\" Copyright (c) 2001-2003 The Open Group, All Rights Reserved
.Dd January 29, 2013
.Dt CPOW 3
.Os
.Sh NAME
.Nm cpow ,
.Nm cpowf ,
.Nm cpowl
.Nd complex power functions
.Sh SYNOPSIS
.In complex.h
.Ft double complex
.Fn cpow "double complex x" "double complex y"
.Ft float complex
.Fn cpowf "float complex x" "float complex y"
.Ft long double complex
.Fn cpowl "long double complex x" "long double complex y"
.Sh DESCRIPTION
These functions compute the complex power function x**y,
with a branch cut for the first
parameter along the negative real axis.
.Sh RETURN VALUES
These functions return the complex power function value.
.Sh ERRORS
No errors are defined.
.Sh SEE ALSO
.Xr cabs 3 ,
.Xr csqrt 3 ,
.St -p1003.1-2001
.Aq Pa complex.h
.Sh COPYRIGHT
Portions of this text are reprinted and reproduced in electronic form
from IEEE Std 1003.1, 2003 Edition, Standard for Information Technology
-- Portable Operating System Interface (POSIX), The Open Group Base
Specifications Issue 6, Copyright (C) 2001-2003 by the Institute of
Electrical and Electronics Engineers, Inc and The Open Group.
In the
event of any discrepancy between this version and the original IEEE and
The Open Group Standard, the original IEEE and The Open Group Standard
is the referee document.
The original Standard can be obtained online at
http://www.opengroup.org/unix/online.html .
