#!/bin/sh

makeone() {
	local name="$(basename "$1" .exe)"
	case $name in
	*instal*|*patch*|*update*|*setup*)
		;;
	*)
		return;;
	esac
cat << _EOF > ${1%.exe}.exe.manifest
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- $NetBSD: mkmanifest,v 1.1 2013/02/17 00:36:40 christos Exp $ -->
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <assemblyIdentity version="1.0.0.0"
     processorArchitecture="X86"
     name="$name"
     type="win32"/>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
</assembly>
_EOF
}

for i
do
	makeone "$i"
done
