#	$NetBSD: Makefile,v 1.3 2002/09/18 14:00:38 lukem Exp $

NOMAN=	# defined

PROG=	lessecho
SRCS=   lessecho.c version.c
CPPFLAGS+=-I${.CURDIR}/../less
.PATH: ${.CURDIR}/../less

.include <bsd.prog.mk>
