# Makefile for the boot stuff.

.include <bsd.own.mk>

SUBDIR = arch/i386/stand/mbr
SUBDIR+= arch/i386/stand/bootxx
SUBDIR+= arch/i386/stand/boot
SUBDIR+= arch/i386/stand/cdboot
SUBDIR+= ufs

.include <bsd.subdir.mk>
