#	$NetBSD: Makefile,v 1.6 2005/12/11 12:21:14 christos Exp $

INCSDIR= /usr/include/dev/ata

# Only install includes which are used by userland
INCS=	atareg.h atavar.h satareg.h

.include <bsd.kinc.mk>
