MAN=	access.2 alarm.2 brk.2 chdir.2 chmod.2 chown.2 chroot.2 \
	close.2 creat.2 dup.2 execve.2 exit.2 fcntl.2 fork.2 \
	getgid.2 getitimer.2 getpid.2 getpriority.2 gettimeofday.2 \
	getuid.2 intro.2 ioctl.2 kill.2 link.2 lseek.2 mkdir.2 \
	mknod.2 mount.2 open.2 pause.2 pipe.2 ptrace.2 read.2 \
	readlink.2 reboot.2 rename.2 rmdir.2 select.2 setsid.2 \
	setuid.2 sigaction.2 sigpending.2 sigprocmask.2 \
	sigsuspend.2 stat.2 svrctl.2 symlink.2 sync.2 time.2 \
	times.2 truncate.2 umask.2 uname.2 unlink.2 utime.2 \
	wait.2 write.2

.include <minix.man.mk>
.include <minix.subdir.mk>
