#	$NetBSD: Makefile,v 1.11 2010/02/06 23:45:25 he Exp $
#	@(#)Makefile	8.1 (Berkeley) 5/31/93

PROG=	rain
MAN=	rain.6
DPADD=	${LIBCURSES} ${LIBTERMINFO}
LDADD=	-lcurses -lterminfo

.include <bsd.prog.mk>
