INCSDIR=	/usr/include/ddekit

INCS+=	assert.h initcall.h memory.h  pgtab.h \
        thread.h attribs.h inline.h  printf.h \
        timer.h condvar.h interrupt.h panic.h \
        resources.h  types.h  debug.h  lock.h \
        pci.h semaphore.h usb.h ddekit.h

SUBDIR+=	minix

.include <bsd.kinc.mk>
