#	$NetBSD: Makefile,v 1.1 2009/07/31 19:16:45 pooka Exp $
#

.PATH:	${.CURDIR}/../../../../miscfs/fdesc

LIB=	rumpfs_fdesc

SRCS=	fdesc_vfsops.c fdesc_vnops.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
