#	$NetBSD: Makefile,v 1.6 2006/05/19 19:11:12 christos Exp $

#Uncomment the next line to enable the new .init fallthru
CPPFLAGS+=	-I${.CURDIR}/../sparc_elf

ELFSIZE=64

.include "${.CURDIR}/../common_elf/Makefile.inc"
