#	$NetBSD: Makefile,v 1.1 2009/12/01 09:01:46 uebayasi Exp $

HOSTPROGNAME=	${_TOOL_PREFIX}pkg_admin
HOST_SRCDIR=	external/bsd/pkg_install/sbin/pkg_admin

.include "${.CURDIR}/../Makefile.inc"

.include "${.CURDIR}/../../Makefile.host"
