#	$NetBSD: Makefile,v 1.8 2008/09/26 18:56:43 apb Exp $
#	@(#)Makefile	8.1 (Berkeley) 5/31/93

NOMAN=		# defined

PROG=		unstr
CPPFLAGS+=	-I${.CURDIR}/../strfile

.include "../../Makefile.inc"
.include <bsd.prog.mk>
