#!/bin/sh
#
# $NetBSD: NETWORKING,v 1.2 2002/03/22 04:33:57 thorpej Exp $
#

# PROVIDE: NETWORKING NETWORK

#	This is a dummy dependency, for services which require networking
#	to be operational before starting.
