#!/bin/sh

INSTALL="install -o bin"
CCACHE=config.cache
rm -f $CCACHE
if [ -f Makefile ] 
then	make distclean
fi
L=libfl.a
YACC=/usr/bin/yacc RANLIB=true AR=ar CONFIG_SHELL=/bin/bigsh CC=cc /bin/bigsh ./configure 
make clean all

$INSTALL -m 755 flex /usr/bin
$INSTALL -l /usr/bin/flex /usr/bin/flex++
$INSTALL FlexLexer.h /usr/local/include
$INSTALL libfl.a /usr/lib/i386

if [ -f /usr/gnu/bin/gcc ]
then	PATH=/usr/gnu/bin:$PATH
	rm -f $CCACHE
	YACC=/usr/bin/yacc CC=gcc CONFIG_SHELL=/bin/bigsh  AR=gar /bin/bigsh ./configure 
	make clean $L
	$INSTALL libfl.a /usr/gnu/lib
fi
