#	$NetBSD: Makefile,v 1.7 2002/09/18 06:16:41 lukem Exp $
#	@(#)Makefile	8.1 (Berkeley) 5/31/93

NOMAN=		# defined

PROG=		snscore
CPPFLAGS+=	-I${.CURDIR}/../snake
HIDEGAME=	hidegame

.include "../../Makefile.inc"
.include <bsd.prog.mk>
