# Makefile for lib/ack/libp.

CFLAGS	= -O -I../h -wo
CC1	= $(CC) $(CFLAGS) -c

LIBRARIES = libp

libp_OBJECTS	= \
	abi.o \
	abl.o \
	abr.o \
	arg.o \
	ass.o \
	asz.o \
	atn.o \
	bcp.o \
	bts.o \
	buff.o \
	catch.o \
	clock.o \
	cls.o \
	cvt.o \
	diag.o \
	dis.o \
	efl.o \
	eln.o \
	encaps.o \
	exp.o \
	fef.o \
	fif.o \
	get.o \
	gto.o \
	head_pc.o \
	hlt.o \
	hol0.o \
	incpt.o \
	ini.o \
	log.o \
	mdi.o \
	mdl.o \
	new.o \
	nfa.o \
	nobuff.o \
	notext.o \
	opn.o \
	outcpt.o \
	pac.o \
	pclose.o \
	pcreat.o \
	pentry.o \
	perrno.o \
	pexit.o \
	popen.o \
	put.o \
	rcka.o \
	rdc.o \
	rdi.o \
	rdl.o \
	rdr.o \
	rf.o \
	rln.o \
	rnd.o \
	sav.o \
	sig.o \
	sin.o \
	sqt.o \
	string.o \
	trap.o \
	trp.o \
	unp.o \
	uread.o \
	uwrite.o \
	wdw.o \
	wf.o \
	wrc.o \
	wrf.o \
	wri.o \
	wrl.o \
	wrr.o \
	wrs.o \
	wrz.o \

include ../../Makefile.ack.inc
