# $NetBSD: md.cats,v 1.3 2013/02/08 15:13:04 christos Exp $
./usr/X11R7/lib/modules/extensions/libcfb32_g.a		-unknown-	obsolete
./usr/X11R7/lib/modules/extensions/libcfb_g.a		-unknown-	obsolete
./usr/X11R7/lib/modules/extensions/libdbe_g.a		-unknown-	debuglib,xorg
./usr/X11R7/lib/modules/extensions/libdri2_g.a		-unknown-	debuglib,xorg
./usr/X11R7/lib/modules/extensions/libdri_g.a		-unknown-	debuglib,xorg
./usr/X11R7/lib/modules/extensions/libextmod_g.a	-unknown-	debuglib,xorg
./usr/X11R7/lib/modules/extensions/libglx_g.a		-unknown-	debuglib,xorg
./usr/X11R7/lib/modules/extensions/libmfb_g.a		-unknown-	obsolete
./usr/X11R7/lib/modules/extensions/librecord_g.a	-unknown-	debuglib,xorg
./usr/X11R7/lib/modules/extensions/libshadow_g.a	-unknown-	debuglib,xorg
./usr/X11R7/lib/modules/extensions/libxtrap_g.a		-unknown-	obsolete
./usr/X11R7/lib/modules/fonts/libfreetype_g.a		-unknown-	obsolete
./usr/X11R7/lib/modules/fonts/libtype1_g.a		-unknown-	obsolete
./usr/X11R7/lib/modules/libexa_g.a			-unknown-	debuglib,xorg
./usr/X11R7/lib/modules/libfb_g.a			-unknown-	debuglib,xorg
./usr/X11R7/lib/modules/libi2c_g.a			-unknown-	debuglib,xorg
./usr/X11R7/lib/modules/libint10_g.a			-unknown-	obsolete
./usr/X11R7/lib/modules/libpcidata_g.a			-unknown-	obsolete
./usr/X11R7/lib/modules/libscanpci_g.a			-unknown-	obsolete
./usr/X11R7/lib/modules/libshadowfb_g.a			-unknown-	debuglib,xorg
./usr/X11R7/lib/modules/libvbe_g.a			-unknown-	debuglib,xorg
./usr/X11R7/lib/modules/libvgahw_g.a			-unknown-	debuglib,xorg
./usr/X11R7/lib/modules/libxaa_g.a			-unknown-	debuglib,xorg
./usr/X11R7/lib/modules/libxf1bpp_g.a			-unknown-	obsolete
./usr/X11R7/lib/modules/libxf4bpp_g.a			-unknown-	obsolete
./usr/X11R7/lib/modules/libxf8_16bpp_g.a		-unknown-	obsolete
./usr/X11R7/lib/modules/libxf8_32bpp_g.a		-unknown-	obsolete
./usr/libdata/debug/usr/X11R7/bin/Xorg.debug		-unknown-	debug,xorg
./usr/libdata/debug/usr/X11R7/bin/Xorg.debug	-unknown-	xorg,debug
./usr/libdata/debug/usr/X11R7/bin/cvt.debug		-unknown-	debug,xorg
./usr/libdata/debug/usr/X11R7/bin/cvt.debug	-unknown-	xorg,debug
./usr/libdata/debug/usr/X11R7/bin/gtf.debug		-unknown-	debug,xorg
./usr/libdata/debug/usr/X11R7/bin/gtf.debug	-unknown-	xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/apm_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/ark_drv.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/ast_drv.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/ati_drv.so.6.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/chips_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/cirrus_alpine.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/cirrus_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/cirrus_laguna.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/glint_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/i128_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/i740_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/kbd_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libapm_drv.so.1.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libark_drv.so.0.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libast_drv.so.0.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libati_drv.so.6.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libchips_drv.so.1.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libcirrus_alpine.so.1.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libcirrus_drv.so.1.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libcirrus_laguna.so.1.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libglint_drv.so.1.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libi128_drv.so.1.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libi740_drv.so.1.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libkbd_drv.so.1.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libmga_drv.so.1.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libmouse_drv.so.1.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libneomagic_drv.so.1.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libnv_drv.so.2.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libradeon_drv.so.6.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libradeonhd_drv.so.1.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libs3_drv.so.0.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libs3virge_drv.so.1.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libsavage_drv.so.2.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libsiliconmotion_drv.so.1.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libtdfx_drv.so.1.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libtga_drv.so.1.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libtrident_drv.so.1.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libtseng_drv.so.1.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libvesa_drv.so.2.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libws_drv.so.1.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libwsfb_drv.so.0.debug	obsolete		xorg,obsolete
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/mga_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/mouse_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/neomagic_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/nv_drv.so.2.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/radeon_drv.so.6.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/radeonhd_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/s3_drv.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/s3virge_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/savage_drv.so.2.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/siliconmotion_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/tdfx_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/tga_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/trident_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/tseng_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/vesa_drv.so.2.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/ws_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/wsfb_drv.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/extensions/libdbe.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/extensions/libdbe.so.0.debug	-unknown-	xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/extensions/libdri.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/extensions/libdri.so.0.debug	-unknown-	xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/extensions/libdri2.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/extensions/libdri2.so.0.debug	-unknown-	xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/extensions/libextmod.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/extensions/libextmod.so.0.debug	-unknown-	xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/extensions/libglx.so.0.debug	-unknown-	xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/extensions/libglx.so.0.debug -unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/extensions/librecord.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/extensions/librecord.so.0.debug	-unknown-	xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/extensions/libshadow.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/extensions/libshadow.so.0.debug	-unknown-	xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libexa.so.0.debug		-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libexa.so.0.debug	-unknown-	xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libfb.so.0.debug		-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libfb.so.0.debug	-unknown-	xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libi2c.so.0.debug		-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libi2c.so.0.debug	-unknown-	xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libshadowfb.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libshadowfb.so.0.debug	-unknown-	xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libvbe.so.0.debug		-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libvbe.so.0.debug	-unknown-	xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libvgahw.so.0.debug		-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libvgahw.so.0.debug	-unknown-	xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libxaa.so.0.debug		-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libxaa.so.0.debug	-unknown-	xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libxf8_16bpp.so.0.debug	-unknown-		obsolete
