#	$NetBSD: Makefile,v 1.4 2014/08/07 08:24:23 hannken Exp $
#

.PATH:  ${.CURDIR}/../../../../fs/efs

LIB=	rumpfs_efs

SRCS=	efs_genfs.c efs_subr.c efs_vfsops.c efs_vnops.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
