# Makefile for usr.bin

.include <bsd.own.mk>

# NetBSD imports
SUBDIR= indent m4 stat tic sed mkdep uniq

# Non-NetBSD imports
SUBDIR+= ministat mkimage

# Minix commands
SUBDIR+= top

.include <bsd.subdir.mk>
