# $NetBSD: Makefile,v 1.3 2014/12/02 19:48:21 christos Exp $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/sys

#__MINIX: Unsupported: net netatalk netinet netinet6
TESTS_SUBDIRS+= 	rc

.include <bsd.test.mk>
