#	$NetBSD: Makefile,v 1.1 2010/03/08 12:46:33 pooka Exp $
#

PROG=	rump_nqmfs

LDADD+=	-lrumpfs_mfs -lrumpfs_ffs

ISRUMP=		# affirmative
NOMAN=		# si, signor
RUMP_DISKFS=	# well, uh, yea, but there's ffs

.include <bsd.prog.mk>
