#	$NetBSD: Makefile,v 1.5.32.1 2009/12/03 17:38:36 snj Exp $

.include <bsd.own.mk>

PROG=	nsupdate
MAN=	nsupdate.1
BINDIR=	/usr/bin

.include "${.CURDIR}/../Makefile.inc"

DIST=${IDIST}/bin/nsupdate

.PATH: ${DIST}

.include <bsd.prog.mk>
