SUBDIR=		v3

.if !defined(HOSTPROGNAME)
#SUBDIR+=	v1 v2	# Original V1 and V2 file systems
#SUBDIR+=	v1l v2l	# Linux-extended variants
#SUBDIR+=	mfs3v2	# V2 as handled by regular MINIX 3.x; hacky
.endif

.include <bsd.subdir.mk>