#	$NetBSD: Makefile,v 1.13 2006/06/02 19:44:48 mrg Exp $
#	from: @(#)Makefile	8.1 (Berkeley) 6/6/93

.include <bsd.own.mk>

PROG=	sed
SRCS=	compile.c main.c misc.c process.c
WARNS=	2

.include <bsd.prog.mk>
