# $NetBSD: Makefile,v 1.7 2013/08/11 22:09:40 joerg Exp $

NOMAN=	# defined

.PATH: ${.CURDIR}/generated

# pull LOCALEDIR and other declarations
.include <bsd.own.mk>

LOCALEFILE=	LC_MONETARY
CATEGORY=	monetary

.include "${.CURDIR}/../Makefile.locale"
.include "${.CURDIR}/../Makefile.common"
