.include <bsd.own.mk>

.PATH: ${MINIXSRCDIR}/common/include

INCS+= 	minix/ansi.h minix/bitmap.h minix/callnr.h minix/com.h \
	minix/compiler.h minix/config.h minix/const.h minix/debug.h \
	minix/devio.h minix/ds.h minix/endpoint.h minix/gcov.h \
	minix/ioctl.h minix/ipc.h minix/ipcconst.h minix/keymap.h \
	minix/limits.h minix/minlib.h minix/portio.h minix/priv.h \
	minix/profile.h minix/rs.h minix/safecopies.h minix/sef.h \
	minix/spin.h minix/sys_config.h minix/sysinfo.h minix/syslib.h \
	minix/sysutil.h minix/timers.h minix/type.h minix/vm.h


