#	$NetBSD: Makefile,v 1.266 2012/08/08 14:13:46 christos Exp $
#	from: @(#)Makefile	5.20 (Berkeley) 6/12/93

.include <bsd.own.mk>

# NetBSD imports
SUBDIR= \
	chroot \
	installboot \
	mtree \
	pwd_mkdb postinstall \
	user \
	vipw \
	zic

# LSC MINIX Specific
SUBDIR+= mkfs.mfs

.include <bsd.subdir.mk>
