MAN=	accept.2 access.2 bind.2 brk.2 chdir.2 chmod.2 chown.2 \
	chroot.2 close.2 connect.2 creat.2 dup.2 execve.2 exit.2 fcntl.2 \
	fork.2 getgid.2 getitimer.2 getnucred.2 getpeereid.2 \
	getpeername.2 getpid.2 getpriority.2 getsockname.2 getsockopt.2 \
	gettimeofday.2 getuid.2 intro.2 ioctl.2 kill.2 link.2 listen.2 \
	lseek.2 mkdir.2 mknod.2 mount.2 open.2 ptrace.2 \
	read.2 readlink.2 recv.2 recvfrom.2 recvmsg.2 rename.2 \
	rmdir.2 select.2 send.2 sendmsg.2 sendto.2 setsid.2 \
	setsockopt.2 setuid.2 shutdown.2 sigaction.2 sigpending.2 \
	sigprocmask.2 sigsuspend.2 socket.2 socketpair.2 \
	svrctl.2 symlink.2 sync.2 time.2 truncate.2 \
	umask.2 uname.2 unlink.2 utime.2 wait.2 write.2

MLINKS += select.2 FD_CLR.2
MLINKS += select.2 FD_ISSET.2
MLINKS += select.2 FD_SET.2
MLINKS += setuid.2 seteuid.2
MLINKS += setuid.2 setgid.2

.include <bsd.man.mk>
