.TH RECVFROM 2
.SH NAME
recvfrom \- receive a message through a socket
.SH SYNOPSIS
.ft B
#include <sys/socket.h>

.in +5
.ti -5
ssize_t recvfrom(int \fIsd\fP, void * \fImsg\fP, size_t \fImsg_len\fP, int \fIflags\fP, struct sockaddr * \fIsrc_addr\fP, socklet_t * \fIsrc_addr_len\fP);
.br
.ft P
.SH DESCRIPTION
recvfrom() receives a message from another socket. It may be
used with connectionless and connection oriented sockets.
At present, minix doesn't support setting \fIflags\fP to any
value other than 0.
.SH RETURN VALUES
On success, this function returns 0. On error, -1 is returned and
\fIerrno\fP is set.
.SH ERRORS
.TP 15
[ENOSYS]
The operation is not implemented for the given socket.
.TP 15
[EPIPE]
The socket is shutdown for reading.
.SH SEE ALSO
.BR socket(2),
.BR send(2)
.BR sendto(2)
.BR recv(2)
