# $NetBSD: Makefile,v 1.3 2005/12/11 12:17:48 christos Exp $

# MINIX (LSC this still needed?)
# Adding cleaning of specific target? -D_MINIX is not defined at top level ?
PROG=	boot_monitor
CLEANFILES= lib

CPPFLAGS+= -D_MINIX

.include <../Makefile.boot>
