#	$NetBSD: Makefile,v 1.3 2003/06/14 17:57:26 wiz Exp $

HOSTPROGNAME=	${_TOOL_PREFIX}makewhatis
HOST_SRCDIR=	libexec/makewhatis

CPPFLAGS+=	-DNROFF="\"nbnroff\""

.include "${.CURDIR}/../Makefile.host"
