#	$NetBSD: Makefile,v 1.6 2005/12/11 12:23:50 christos Exp $

INCSDIR= /usr/include/dev/scsipi

# Only install includes which are used by userland
INCS=	scsi_spc.h
INCS+=	scsipi_all.h scsi_all.h scsipi_cd.h scsipi_debug.h scsi_disk.h 	\
	scsipiconf.h scsiconf.h ses.h

.include <bsd.kinc.mk>
