
INCSDIR= /usr/include/sys

INCS+= elf64.h elf_common.h elf_generic.h \
	ioc_block.h ioc_fbd.h ioc_file.h ioc_tape.h ioc_disk.h \
	ioc_memory.h ioc_sound.h ioc_tty.h \
	kbdio.h mtio.h svrctl.h video.h vm.h procfs.h elf_core.h exec_elf.h \
	disk.h dkio.h ioccom.h mutex.h iostat.h disklabel.h disklabel_gpt.h \
	bootblock.h dkbad.h

.include <bsd.kinc.mk>
