.\"	$NetBSD: getfsspecname.3,v 1.5 2015/06/13 19:52:58 dholland Exp $
.\"
.\" Copyright (c) 2012 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Christos Zoulas.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.\"
.Dd August 18, 2014
.Dt GETFSSPECNAME 3
.Os
.Sh NAME
.Nm getfsspecname
.Nd get the underlying wedge name from a label
.Sh LIBRARY
.Lb libutil
.Sh SYNOPSIS
.In util.h
.Ft const char *
.Fn getfsspecname "char *buf" "size_t buflen" "const char *spec"
.Sh DESCRIPTION
The
.Fn getfsspecname
function translates an
.Ft fs_spec
field in the
.Fa spec
argument of the form
.Dq NAME=wedgename
to the underlying
.Xr dk 4
device node, and places the resulting pathname in
.Fa buf
up to len
.Fa buflen .
.Pp
If the
.Fa spec
argument is not of the form
.Dq NAME=wedgename ,
.Fa spec
is copied
to
.Fa buf
and returned.
.Sh RETURN VALUES
On success the absolute pathname of the underlying wedge device is returned,
or the original
.Fa spec
argument.
On failure
.Dv NULL
is returned and
.Fa buf
contains the reason for the error.
.Sh SEE ALSO
.Xr fstab 5
.Sh HISTORY
The
.Fn getfsspecname
function appeared in
.Nx 7.0 .
