.\" $NetBSD: ttymsg.3,v 1.13 2013/01/16 06:44:27 wiz Exp $
.\"
.\" Copyright (c) 1996 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd January 15, 2013
.Dt TTYMSG 3
.Os
.Sh NAME
.Nm ttymsg
.Nd ttymsg utility function
.Sh LIBRARY
.Lb libutil
.Sh SYNOPSIS
.In util.h
.Ft char *
.Fn ttymsg "struct iovec *iov" "int iovlen" "const char *tty" "int tmout"
.Sh DESCRIPTION
The
.Fn ttymsg
function is used by
programs such as
.Xr talkd 8 ,
.Xr syslogd 8 ,
.Xr wall 1 ,
etc., to display the contents of a uio structure on a terminal.
.Fn ttymsg
forks and finishes in the child if the write would block after
waiting up to
.Fa tmout
seconds.
.Sh RETURN VALUES
.Fn ttymsg
returns a pointer to an error string on unexpected
error; the string is not newline-terminated.
Various "normal" errors are
ignored (exclusive-use, lack of permission, etc.).
.Sh SEE ALSO
.Xr writev 2
.Sh BUGS
.Nm
could grow some flags and a username/uid who is the expected owner
of the tty.
If the flags say so then the owner should be checked against the tty
owner, and the message should not be sent if there is a mismatch.
Also another flag could say check against group writable, and don't
send a message.
