#	$NetBSD: Makefile,v 1.1 2006/06/18 05:16:41 gdamore Exp $

HOSTPROGNAME=	${_TOOL_PREFIX}sed
HOST_SRCDIR=	usr.bin/sed

.ifdef __MINIX
SYMLINKS=	# defined so usr.bin/sed/Makefile does not set it
.endif

.include "${.CURDIR}/../Makefile.host"
