#	$NetBSD: Makefile,v 1.2 2004/01/12 01:18:12 lukem Exp $

.include <bsd.own.mk>

#Not building the pxe client for now
#.if ${MKSHARE} != "no"
#FILES=	pxe.defs
#FILESDIR=/usr/share/dhcpd
#.endif

.include <bsd.prog.mk>
