#	$NetBSD: Makefile,v 1.8 2008/04/02 01:34:36 dyoung Exp $

INCSDIR= /usr/include/dev/isa

# Only install includes which are used by userland
INCS=	isvio.h satlinkio.h spkrio.h wtreg.h

.include <bsd.kinc.mk>
