/*	$NetBSD: rumpkern_syscalls.c,v 1.3 2015/06/18 15:19:50 pooka Exp $	*/

/* AUTOMATICALLY GENERATED BY makerumpsyscalls.sh */

#include <sys/cdefs.h>
__KERNEL_RCSID(0, "$NetBSD: rumpkern_syscalls.c,v 1.3 2015/06/18 15:19:50 pooka Exp $");

#include <sys/param.h>

#include "rump_private.h"

extern sy_call_t sys_read;
extern sy_call_t sys_write;
extern sy_call_t sys_close;
extern sy_call_t sys_getpid_with_ppid;
extern sy_call_t sys_setuid;
extern sy_call_t sys_getuid_with_euid;
extern sy_call_t sys_geteuid;
extern sy_call_t sys_getppid;
extern sy_call_t sys_dup;
extern sy_call_t sys_pipe;
extern sy_call_t sys_getegid;
extern sy_call_t sys_getgid_with_egid;
extern sy_call_t sys___getlogin;
extern sy_call_t sys___setlogin;
extern sy_call_t sys_ioctl;
extern sy_call_t sys_getgroups;
extern sy_call_t sys_setgroups;
extern sy_call_t sys_getpgrp;
extern sy_call_t sys_setpgid;
extern sy_call_t sys_dup2;
extern sy_call_t sys_fcntl;
extern sy_call_t sys_readv;
extern sy_call_t sys_writev;
extern sy_call_t sys_setreuid;
extern sy_call_t sys_setregid;
extern sy_call_t sys_flock;
extern sy_call_t sys_setsid;
extern sy_call_t sys_setgid;
extern sy_call_t sys_setegid;
extern sy_call_t sys_seteuid;
extern sy_call_t sys_fpathconf;
extern sy_call_t sys_getrlimit;
extern sy_call_t sys_setrlimit;
extern sy_call_t sys___sysctl;
extern sy_call_t sys_getpgid;
extern sy_call_t sys_reboot;
extern sy_call_t sys_poll;
extern sy_call_t sys_timer_create;
extern sy_call_t sys_timer_delete;
extern sy_call_t sys_timer_getoverrun;
extern sy_call_t sys_modctl;
extern sy_call_t sys_getsid;
extern sy_call_t sys_fktrace;
extern sy_call_t sys_issetugid;
extern sy_call_t sys_utrace;
extern sy_call_t sys_kqueue;
extern sy_call_t sys___posix_fadvise50;
extern sy_call_t sys___select50;
extern sy_call_t sys___gettimeofday50;
extern sy_call_t sys___settimeofday50;
extern sy_call_t sys___adjtime50;
extern sy_call_t sys___setitimer50;
extern sy_call_t sys___getitimer50;
extern sy_call_t sys___clock_gettime50;
extern sy_call_t sys___clock_settime50;
extern sy_call_t sys___clock_getres50;
extern sy_call_t sys___nanosleep50;
extern sy_call_t sys___kevent50;
extern sy_call_t sys___pselect50;
extern sy_call_t sys___pollts50;
extern sy_call_t sys___fstat50;
extern sy_call_t sys___timer_settime50;
extern sy_call_t sys___timer_gettime50;
extern sy_call_t sys_pipe2;
extern sy_call_t sys_dup3;
extern sy_call_t sys_kqueue1;
extern sy_call_t sys_clock_nanosleep;

static const struct rump_onesyscall mysys[] = {
	{ 3,	sys_read },
	{ 4,	sys_write },
	{ 6,	sys_close },
	{ 20,	sys_getpid_with_ppid },
	{ 23,	sys_setuid },
	{ 24,	sys_getuid_with_euid },
	{ 25,	sys_geteuid },
	{ 39,	sys_getppid },
	{ 41,	sys_dup },
	{ 42,	sys_pipe },
	{ 43,	sys_getegid },
	{ 47,	sys_getgid_with_egid },
	{ 49,	sys___getlogin },
	{ 50,	sys___setlogin },
	{ 54,	sys_ioctl },
	{ 79,	sys_getgroups },
	{ 80,	sys_setgroups },
	{ 81,	sys_getpgrp },
	{ 82,	sys_setpgid },
	{ 90,	sys_dup2 },
	{ 92,	sys_fcntl },
	{ 120,	sys_readv },
	{ 121,	sys_writev },
	{ 126,	sys_setreuid },
	{ 127,	sys_setregid },
	{ 131,	sys_flock },
	{ 147,	sys_setsid },
	{ 181,	sys_setgid },
	{ 182,	sys_setegid },
	{ 183,	sys_seteuid },
	{ 192,	sys_fpathconf },
	{ 194,	sys_getrlimit },
	{ 195,	sys_setrlimit },
	{ 202,	sys___sysctl },
	{ 207,	sys_getpgid },
	{ 208,	sys_reboot },
	{ 209,	sys_poll },
	{ 235,	sys_timer_create },
	{ 236,	sys_timer_delete },
	{ 239,	sys_timer_getoverrun },
	{ 246,	sys_modctl },
	{ 286,	sys_getsid },
	{ 288,	sys_fktrace },
	{ 305,	sys_issetugid },
	{ 306,	sys_utrace },
	{ 344,	sys_kqueue },
	{ 416,	sys___posix_fadvise50 },
	{ 417,	sys___select50 },
	{ 418,	sys___gettimeofday50 },
	{ 419,	sys___settimeofday50 },
	{ 421,	sys___adjtime50 },
	{ 425,	sys___setitimer50 },
	{ 426,	sys___getitimer50 },
	{ 427,	sys___clock_gettime50 },
	{ 428,	sys___clock_settime50 },
	{ 429,	sys___clock_getres50 },
	{ 430,	sys___nanosleep50 },
	{ 435,	sys___kevent50 },
	{ 436,	sys___pselect50 },
	{ 437,	sys___pollts50 },
	{ 440,	sys___fstat50 },
	{ 446,	sys___timer_settime50 },
	{ 447,	sys___timer_gettime50 },
	{ 453,	sys_pipe2 },
	{ 454,	sys_dup3 },
	{ 455,	sys_kqueue1 },
	{ 477,	sys_clock_nanosleep },
};

RUMP_COMPONENT(RUMP_COMPONENT_SYSCALL)
{

	rump_syscall_boot_establish(mysys, __arraycount(mysys));
}
