# Makefile for lib/other.

CFLAGS	= -O -D_MINIX -D_POSIX_SOURCE -I../../servers

LIBRARIES = libc

libc_OBJECTS	= \
	_allocmem.o \
	_freemem.o \
	_brk.o \
	_reboot.o \
	_seekdir.o \
	_svrctl.o \
	_getsysinfo.o \
	_getprocnr.o \
	_getnpid.o \
	_getnprocnr.o \
	_getpprocnr.o \
	_devctl.o \
	_findproc.o \
	asynchio.o \
	basename.o \
	configfile.o \
	crypt.o \
	ctermid.o \
	cuserid.o \
	environ.o \
	errno.o \
	fdopen.o \
	ffs.o \
	fslib.o \
	fsversion.o \
	getgrent.o \
	getlogin.o \
	getopt.o \
	getpagesize.o \
	getpass.o \
	getpwent.o \
	getttyent.o \
	getw.o \
	hypot.o \
	itoa.o \
	loadname.o \
	lock.o \
	lrand.o \
	lsearch.o \
	memccpy.o \
	mstats.o \
	mtab.o \
	nlist.o \
	peekpoke.o \
	popen.o \
	putenv.o \
	putw.o \
	random.o \
	setgroups.o \
	settimeofday.o \
	stderr.o \
	strdup.o \
	strtok_r.o \
	swab.o \
	syscall.o \
	sysconf.o \
	telldir.o \
	termcap.o \
	ttyname.o \
	ttyslot.o \
	v8regexp.o \
	v8regsub.o \

include ../Makefile.inc
