# Makefile for urlget
#
# 07/02/96 Initial Release	Michael Temari, <temari@ix.netcom.com>
#

PROG=	urlget
SRCS=	urlget.c net.c
LINKS+=	${BINDIR}/urlget ${BINDIR}/httpget
LINKS+=	${BINDIR}/urlget ${BINDIR}/ftpget
MAN=

.include <bsd.prog.mk>
