#	$NetBSD: Makefile,v 1.2.34.1 2011/01/09 20:43:31 riz Exp $

SUBDIR= dnssec-dsfromkey dnssec-keyfromlabel dnssec-keygen dnssec-signzone \
	dnssec-settime dnssec-revoke

.include "Makefile.inc"

.include <bsd.subdir.mk>
