# Makefile for all system servers.
#

.include <bsd.own.mk>

SUBDIR=	ds hgfs inet init ipc is iso9660fs mfs pfs pm rs sched vfs vm

IMAGE_SUBDIR=	ds init mfs pfs pm rs sched vfs vm

.include <bsd.subdir.mk>
