#!/bin/sh

make >/dev/null

echo -n "Kernel test (sys_padconf): "
minix-service up `pwd`/padconftest -config system.conf -label padconftest -script /etc/rs.single
r=$?

if [ $r -ne 0 ]; then
  echo "failure"
  exit 1
fi

echo "ok"
