#	$NetBSD: Makefile,v 1.7 2004/02/08 13:16:25 jsm Exp $
#	@(#)Makefile	8.1 (Berkeley) 5/31/93

PROG=		primes
SRCS=		pattern.c pr_tbl.c primes.c
MAN=		primes.6
DPADD=		${LIBM}
LDADD=		-lm

.include <bsd.prog.mk>
