#	$NetBSD: Makefile,v 1.8 2014/10/02 21:36:37 ast Exp $
#	@(#)Makefile	8.1 (Berkeley) 5/31/93

PROG=		primes
SRCS=		pattern.c pr_tbl.c primes.c spsp.c
MAN=		primes.6
DPADD=		${LIBM}
LDADD=		-lm

.include <bsd.prog.mk>
