.\"	$NetBSD: primes.6,v 1.5 2014/10/04 13:15:50 wiz Exp $
.\"
.\" Copyright (c) 1989, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" Landon Curt Noll.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)factor.6	8.1 (Berkeley) 5/31/93
.\"
.\"
.\" By Landon Curt Noll, http://www.isthe.com/chongo/index.html /\oo/\
.\"
.Dd February 3, 2008
.Dt PRIMES 6
.Os
.Sh NAME
.Nm primes
.Nd generate primes
.Sh SYNOPSIS
.Nm primes
.Op Fl dh
.Op Ar start Op Ar stop
.Sh DESCRIPTION
The
.Nm
utility prints primes in ascending order, one per line, starting
at or above
.Ar start
and continuing until, but not including
.Ar stop .
The
.Ar start
value must be at least 0 and not greater than
.Ar stop .
The
.Ar stop
value must not be greater than 3825123056546413050.
The default value of
.Ar stop
is 3825123056546413050.
.Pp
When the
.Nm
utility is invoked with no arguments,
.Ar start
is read from standard input and
.Ar stop
is taken to be 3825123056546413050.
The
.Ar start
value may be preceded by a single
.Sq \&+ .
The
.Ar start
value is terminated by a non-digit character (such as a newline).
The input line must not be longer than 255 characters.
.Pp
When given the
.Fl d
argument,
.Nm
prints the difference between the current and the previous prime.
.Pp
When given the
.Fl h
argument,
.Nm
prints the prime numbers in hexadecimal.
.Sh DIAGNOSTICS
Out of range or invalid input results in
an appropriate error message to standard error.
.Sh AUTHORS
.An -nosplit
Originally by
.An Landon Curt Noll ,
extended to some 64-bit primes by
.An Colin Percival .
.Sh CAVEATS
This
.Nm
program won't get you a world record.
.Pp
The program is not able to list primes between
3825123056546413050 and 18446744073709551615 (2^64
- 1) as it relies on strong pseudoprime tests after
sieving, and it is yet unknown how many of those
tests are needed to prove primality for integers
larger than 3825123056546413050.
