#	$NetBSD: Makefile,v 1.2 2014/07/20 13:58:05 hannken Exp $
#

.PATH:  ${.CURDIR}/../../../../miscfs/kernfs

LIB=	rumpfs_kernfs

SRCS=	kernfs_vfsops.c kernfs_vnops.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
