# $NetBSD: md.cats,v 1.11 2011/08/03 01:43:25 mrg Exp $
./usr/X11R6/include/xf86Optrec.h			-unknown-	x11
./usr/X11R6/include/xf86Parser.h			-unknown-	x11
./usr/X11R6/man/cat3/XF86VidMode.0			-unknown-	.cat,x11
./usr/X11R6/man/cat3/XF86VidModeDeleteModeLine.0	-unknown-	.cat,x11
./usr/X11R6/man/cat3/XF86VidModeGetAllModeLines.0	-unknown-	.cat,x11
./usr/X11R6/man/cat3/XF86VidModeGetDotClocks.0		-unknown-	.cat,x11
./usr/X11R6/man/cat3/XF86VidModeGetGamma.0		-unknown-	.cat,x11
./usr/X11R6/man/cat3/XF86VidModeGetGammaRamp.0		-unknown-	.cat,x11
./usr/X11R6/man/cat3/XF86VidModeGetGammaRampSize.0	-unknown-	.cat,x11
./usr/X11R6/man/cat3/XF86VidModeGetModeLine.0		-unknown-	.cat,x11
./usr/X11R6/man/cat3/XF86VidModeGetMonitor.0		-unknown-	.cat,x11
./usr/X11R6/man/cat3/XF86VidModeGetPermissions.0	-unknown-	.cat,x11
./usr/X11R6/man/cat3/XF86VidModeGetViewPort.0		-unknown-	.cat,x11
./usr/X11R6/man/cat3/XF86VidModeLockModeSwitch.0	-unknown-	.cat,x11
./usr/X11R6/man/cat3/XF86VidModeModModeLine.0		-unknown-	.cat,x11
./usr/X11R6/man/cat3/XF86VidModeQueryExtension.0	-unknown-	.cat,x11
./usr/X11R6/man/cat3/XF86VidModeQueryVersion.0		-unknown-	.cat,x11
./usr/X11R6/man/cat3/XF86VidModeSetClientVersion.0	-unknown-	.cat,x11
./usr/X11R6/man/cat3/XF86VidModeSetGamma.0		-unknown-	.cat,x11
./usr/X11R6/man/cat3/XF86VidModeSetGammaRamp.0		-unknown-	.cat,x11
./usr/X11R6/man/cat3/XF86VidModeSetViewPort.0		-unknown-	.cat,x11
./usr/X11R6/man/cat3/XF86VidModeSwitchMode.0		-unknown-	.cat,x11
./usr/X11R6/man/cat3/XF86VidModeSwitchToMode.0		-unknown-	.cat,x11
./usr/X11R6/man/cat3/XF86VidModeValidateModeLine.0	-unknown-	.cat,x11
./usr/X11R6/man/cat4/fpit.0				-unknown-	.cat,x11
./usr/X11R6/man/html3/XF86VidMode.html			-unknown-	html,x11
./usr/X11R6/man/html3/XF86VidModeDeleteModeLine.html	-unknown-	html,x11
./usr/X11R6/man/html3/XF86VidModeGetAllModeLines.html	-unknown-	html,x11
./usr/X11R6/man/html3/XF86VidModeGetDotClocks.html	-unknown-	html,x11
./usr/X11R6/man/html3/XF86VidModeGetGamma.html		-unknown-	html,x11
./usr/X11R6/man/html3/XF86VidModeGetGammaRamp.html	-unknown-	html,x11
./usr/X11R6/man/html3/XF86VidModeGetGammaRampSize.html	-unknown-	html,x11
./usr/X11R6/man/html3/XF86VidModeGetModeLine.html	-unknown-	html,x11
./usr/X11R6/man/html3/XF86VidModeGetMonitor.html	-unknown-	html,x11
./usr/X11R6/man/html3/XF86VidModeGetPermissions.html	-unknown-	html,x11
./usr/X11R6/man/html3/XF86VidModeGetViewPort.html	-unknown-	html,x11
./usr/X11R6/man/html3/XF86VidModeLockModeSwitch.html	-unknown-	html,x11
./usr/X11R6/man/html3/XF86VidModeModModeLine.html	-unknown-	html,x11
./usr/X11R6/man/html3/XF86VidModeQueryExtension.html	-unknown-	html,x11
./usr/X11R6/man/html3/XF86VidModeQueryVersion.html	-unknown-	html,x11
./usr/X11R6/man/html3/XF86VidModeSetClientVersion.html	-unknown-	html,x11
./usr/X11R6/man/html3/XF86VidModeSetGamma.html		-unknown-	html,x11
./usr/X11R6/man/html3/XF86VidModeSetGammaRamp.html	-unknown-	html,x11
./usr/X11R6/man/html3/XF86VidModeSetViewPort.html	-unknown-	html,x11
./usr/X11R6/man/html3/XF86VidModeSwitchMode.html	-unknown-	html,x11
./usr/X11R6/man/html3/XF86VidModeSwitchToMode.html	-unknown-	html,x11
./usr/X11R6/man/html3/XF86VidModeValidateModeLine.html	-unknown-	html,x11
./usr/X11R6/man/html4/fpit.html				-unknown-	html,x11
./usr/X11R6/man/man3/XF86VidMode.3			-unknown-	.man,x11
./usr/X11R6/man/man3/XF86VidModeDeleteModeLine.3	-unknown-	.man,x11
./usr/X11R6/man/man3/XF86VidModeGetAllModeLines.3	-unknown-	.man,x11
./usr/X11R6/man/man3/XF86VidModeGetDotClocks.3		-unknown-	.man,x11
./usr/X11R6/man/man3/XF86VidModeGetGamma.3		-unknown-	.man,x11
./usr/X11R6/man/man3/XF86VidModeGetGammaRamp.3		-unknown-	.man,x11
./usr/X11R6/man/man3/XF86VidModeGetGammaRampSize.3	-unknown-	.man,x11
./usr/X11R6/man/man3/XF86VidModeGetModeLine.3		-unknown-	.man,x11
./usr/X11R6/man/man3/XF86VidModeGetMonitor.3		-unknown-	.man,x11
./usr/X11R6/man/man3/XF86VidModeGetPermissions.3	-unknown-	.man,x11
./usr/X11R6/man/man3/XF86VidModeGetViewPort.3		-unknown-	.man,x11
./usr/X11R6/man/man3/XF86VidModeLockModeSwitch.3	-unknown-	.man,x11
./usr/X11R6/man/man3/XF86VidModeModModeLine.3		-unknown-	.man,x11
./usr/X11R6/man/man3/XF86VidModeQueryExtension.3	-unknown-	.man,x11
./usr/X11R6/man/man3/XF86VidModeQueryVersion.3		-unknown-	.man,x11
./usr/X11R6/man/man3/XF86VidModeSetClientVersion.3	-unknown-	.man,x11
./usr/X11R6/man/man3/XF86VidModeSetGamma.3		-unknown-	.man,x11
./usr/X11R6/man/man3/XF86VidModeSetGammaRamp.3		-unknown-	.man,x11
./usr/X11R6/man/man3/XF86VidModeSetViewPort.3		-unknown-	.man,x11
./usr/X11R6/man/man3/XF86VidModeSwitchMode.3		-unknown-	.man,x11
./usr/X11R6/man/man3/XF86VidModeSwitchToMode.3		-unknown-	.man,x11
./usr/X11R6/man/man3/XF86VidModeValidateModeLine.3	-unknown-	.man,x11
./usr/X11R6/man/man4/fpit.4				-unknown-	.man,x11
./usr/libdata/debug/usr/X11R7/bin/Xorg.debug		-unknown-	debug,xorg
./usr/libdata/debug/usr/X11R7/bin/cvt.debug		-unknown-	debug,xorg
./usr/libdata/debug/usr/X11R7/bin/gtf.debug		-unknown-	debug,xorg
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libapm_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libark_drv.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libast_drv.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libati_drv.so.6.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libchips_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libcirrus_alpine.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libcirrus_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libcirrus_laguna.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libglint_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libi128_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libi740_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libkbd_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libmga_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libmouse_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libneomagic_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libnv_drv.so.2.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libradeon_drv.so.6.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libradeonhd_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libs3_drv.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libs3virge_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libsavage_drv.so.2.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libsiliconmotion_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libtdfx_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libtga_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libtrident_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libtseng_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libvesa_drv.so.2.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libws_drv.so.1.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/drivers/libwsfb_drv.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/extensions/libdbe.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/extensions/libdri.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/extensions/libdri2.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/extensions/libextmod.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/extensions/libglx.so.0.debug -unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/extensions/librecord.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/extensions/libshadow.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libexa.so.0.debug		-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libfb.so.0.debug		-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libi2c.so.0.debug		-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libshadowfb.so.0.debug	-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libvbe.so.0.debug		-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libvgahw.so.0.debug		-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libxaa.so.0.debug		-unknown-		xorg,debug
./usr/libdata/debug/usr/X11R7/lib/modules/libxf8_16bpp.so.0.debug	-unknown-		obsolete
