.TH FABS 3 "January 7, 2010"
.UC 4
.SH NAME
fabs, fabsf \- compute absolute value
.SH SYNOPSIS
.nf
.ft B
#include <math.h>

double fabs(double \fIx\fP);
float fabsf(float \fIx\fP);
.fi
.SH DESCRIPTION
\fBfabs\fP and \fBfabsf\fP return the absolute value of their argument.
.SH "RETURN VALUE
The return value is a number with the same magnitude as the argument and with
a positive sign.

