.\"	@(#)getpass.3	6.1 (Berkeley) 5/15/85
.\"
.TH GETPASS 3  "May 15, 1985"
.AT 3
.SH NAME
getpass \- read a password
.SH SYNOPSIS
.nf
.ft B
#include <minix/minlib.h>

char *getpass(const char *\fIprompt\fP)
.fi
.SH DESCRIPTION
.B Getpass
reads a password from the file
.BR /dev/tty ,
or if that cannot be opened, from the standard input,
after prompting with the null-terminated string
.I prompt
and disabling echoing.
A pointer is returned to a null-terminated string
of at most 32 characters, excluding the null.
.SH "SEE ALSO"
.BR crypt (3).
.SH BUGS
The return value points to static data
whose content is overwritten by each call.
