.TH LDEXP 3 "January 7, 2010"
.UC 4
.SH NAME
ldexp, scalbn, scalbnf, scalbln, scalblnf \- compute absolute value
.SH SYNOPSIS
.nf
.ft B
#include <math.h>

double ldexp(double \fIx\fP, int \fIn\fP);
double scalbn(double \fIx\fP, int \fIn\fP);
float scalbnf(float \fIx\fP, int \fIn\fP);
double scalbln(double \fIx\fP, long \fIn\fP);
float scalblnf(float \fIx\fP, long \fIn\fP);
.fi
.SH DESCRIPTION
These functions all compute \fIx\fP * 2^\fIn\fP.
.SH "RETURN VALUE
These functions all return \fIx\fP * 2^\fIn\fP.
