.\"	@(#)rand.3c	6.2 (Berkeley) 9/29/85
.\"
.TH RAND 3 "September 29, 1985"
.AT 3
.SH NAME
rand, srand \- random number generator
.SH SYNOPSIS
.nf
.ft B
#include <stdlib.h>

void srand(unsigned \fIseed\fP)
unsigned rand(void)
.ft R
.fi
.SH DESCRIPTION
.B Rand
uses a multiplicative congruential
random number generator with period
.if t 2\u\s732\s0\d
.if n 2**32
to return successive pseudo-random
numbers in the range from 0 to
.BR RAND_MAX .
.PP
The generator is reinitialized by calling
.B srand
with 1 as argument.
It can be set to a random starting point by calling
.B srand
with whatever you like as argument.
.SH "SEE ALSO"
.BR random (3).
