.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)sleep.3	6.2 (Berkeley) 5/12/86
.\"
.TH SLEEP 3  "August 16, 2009"
.UC 4
.SH NAME
sleep \- suspend execution for interval
.SH SYNOPSIS
.nf
.ft B
#include <unistd.h>

unsigned int sleep(unsigned int \fIseconds\fP)
.fi
.SH DESCRIPTION
The current process is suspended from execution for the number
of seconds specified by the argument.
.PP
The routine is implemented using the 'select' function, so it does not
interfere with alarm timers. If a signal is received, the function returns.
.SH "RETURN VALUE
The amount of time that remains to be slept is returned. This value is 
specified in seconds and rounded up.
.SH "SEE ALSO"
.BR pause (2),
.BR nanosleep (3).
