MAN=	add_route.8 backup.8 boot.8 btrace.8 \
	cdprobe.8 chown.8 cleantmp.8 config.8 cron.8 \
	dhcpd.8 diskctl.8 fbdctl.8 fdisk.8 fingerd.8 \
	getty.8 halt.8 hgfs.8 httpd.8 ifconfig.8 inet.8 init.8 \
	intr.8 irdpd.8 loadramdisk.8 MAKEDEV.8 \
	netconf.8 newroot.8 nonamed.8 \
	ossdevlinks.8 part.8 partition.8 \
	poweroff.8 printroot.8 pr_routes.8 pwdauth.8 rarpd.8 \
	rdate.8 readclock.8 reboot.8 repartition.8 \
	rshd.8  screendump.8 serial-ip.8 service.8 \
	setup.8 shutdown.8 slip.8 srccrc.8 syslogd.8 tcpd.8 \
	unix.8 update.8 usage.8 vbfs.8

MLINKS += httpd.8 in.httpd.8

.include <bsd.man.mk>
.include <bsd.subdir.mk>
