.TH SCREENDUMP 8
.SH NAME
screendump \- write current console screen to standard output
.SH SYNOPSIS
.B screendump
.SH DESCRIPTION
.B Screendump
prints the contents of the console screen to standard output.  It does this
by reading the screen memory, skipping over attribute bytes, omitting
trailing blanks and inserting a newline character at the end of each line.
.SH NOTES
The most common use of 
.BR screendump
is with output redirected to a file. This allows screen displays (including 
output of F-keys) to be captured for inclusion in other documents.
.PP
This version is for IBM-PC architecture only. 
.SH BUGS
A network user captures an image of the main console, not his or her own
screen.  The output will usually not be what you expect if the display is in
hardware scrolling mode, since in that mode the order of the lines in screen
memory may not be the same as what appears on the screen.
If you expect to use 
.BR screendump
to send notes to someone about problems that occur while using 
.BR MINIX
you must remember to toggle to software scrolling before you make the dump.
It will also be necessary to use
.BR su ,
because
.BR /dev/mem
is normally not world readable.
.SH AUTHOR
Kees J. Bot (kjb@cs.vu.nl)
.\" preliminary man file by Al Woodhull (awoodhull@hampshire.edu) 01.08.95
