MAN=	at.1 \
	bsfilt.1 cawf.1 chgrp.1 \
	cmp.1 compress.1 \
	crc.1 crontab.1 dd.1 \
	dhrystone.1 dosdir.1 dosread.1 doswrite.1 \
	eject.1 \
	flexdoc.1 format.1 \
	fsck.mfs.1 host.1 hostaddr.1 ifdef.1 \
	isodir.1 isoinfo.1 isoread.1 \
	loadfont.1 loadkeys.1 logger.1 \
	look.1 lp.1 lspci.1 mail.1  \
	mixer.1 \
	mkproto.1 mount.1 mt.1 \
	playwave.1 prep.1 \
	profile.1 ps.1 rcp.1 recwave.1 \
	remsync.1 rget.1 rlogin.1 rsh.1 rz.1 \
	spell.1 svc.1 svrctl.1 \
	synctree.1 sysenv.1 sz.1 telnet.1 template.1 \
	term.1 termcap.1 tget.1 time.1 \
	truncate.1 umount.1 \
	vol.1 \
	yap.1 linkfarm.1 pkg_view.1

MLINKS += compress.1 uncompress.1
MLINKS += svc.1 ci.1
MLINKS += svc.1 co.1

.include <bsd.man.mk>
