.\"	$NetBSD: explicit_memset.3,v 1.2 2013/08/28 15:46:23 riastradh Exp $
.\"
.\" Copyright (c) 2013 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This documentation is derived from text contributed to The NetBSD
.\" Foundation by Taylor R. Campbell.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd August 28, 2013
.Dt EXPLICIT_MEMSET 3
.Os
.Sh NAME
.Nm explicit_memset
.Nd guarantee writing a byte to a byte string
.Sh LIBRARY
.Lb libc
.Sh SYNOPSIS
.In string.h
.Ft void *
.Fn explicit_memset "void *b" "int c" "size_t len"
.Sh DESCRIPTION
The
.Fn explicit_memset
function writes
.Fa len
bytes of value
.Fa c
(converted to an unsigned char) to the string
.Fa b .
It is guaranteed not to be optimized away by the compiler even if
.Fa b
is no longer used and is about to be freed or go out of scope.
.Sh RETURN VALUES
The
.Fn explicit_memset
function returns the original value of
.Fa b .
.Sh EXAMPLES
Create a buffer on the stack for a secret key, use it, and then zero it
in memory before throwing it away.
.Bd -literal -offset indent
void
f(void)
{
	uint8_t key[32];

	crypto_random(key, sizeof(key));
	do_crypto_stuff(key, sizeof(key));
	\&...

	explicit_memset(key, 0, sizeof(key));
}
.Ed
.Sh SEE ALSO
.Xr consttime_memequal 3 ,
.Xr memset 3
.Sh HISTORY
The
.Fn explicit_memset
function appeared in
.Nx 7.0 .
