#	$NetBSD: Makefile.pcmciadevs,v 1.2 2008/10/19 22:05:23 apb Exp $

.include <bsd.own.mk>

pcmciadevs.h pcmciadevs_data.h: pcmciadevs devlist2h.awk
	/bin/rm -f pcmciadevs.h pcmciadevs_data.h
	${TOOL_AWK} -f devlist2h.awk pcmciadevs
