#	$NetBSD: Makefile,v 1.7 2001/05/06 03:26:39 ichiro Exp $

# use 'make -f Makefile.pcmciadevs' to make pcmciadevs.h and pcmciadevs_data.h

INCSDIR= /usr/include/dev/pcmcia

# Only install includes which are used by userland
INCS=	if_cnwioctl.h if_rayreg.h

.include <bsd.kinc.mk>
