#	$NetBSD: Makefile,v 1.17 2014/06/07 16:37:32 christos Exp $
#	from: @(#)Makefile	8.1 (Berkeley) 6/6/93

.include <bsd.own.mk>
WARNS=6

PROG=	sed
SRCS=	compile.c main.c misc.c process.c

.include <bsd.prog.mk>
