#	$NetBSD: Makefile,v 1.14 2009/04/14 22:15:26 lukem Exp $
#	from: @(#)Makefile	8.1 (Berkeley) 6/6/93

.include <bsd.own.mk>

PROG=	sed
SRCS=	compile.c main.c misc.c process.c

# LSC FIXME Still required?
SYMLINKS?=    ${BINDIR}/sed /bin/sed

.include <bsd.prog.mk>
