#	$NetBSD: Makefile,v 1.2 2006/09/14 23:55:54 cherry Exp $

ELFSIZE=	64

#Uncomment the next line to enable the new .init fallthru
CPPFLAGS+=	-I- -I${.CURDIR}

.include "${.CURDIR}/../common_elf/Makefile.inc"
