MAN=	ACK.7 ascii.7 environ.7 hier.7 man.7 oss_atiaudio.7 \
	oss_audigyls.7 oss_audiopci.7 oss_cmi878x.7 oss_cmpci.7 \
	osscore.7 oss_cs4281.7 oss_cs461x.7 oss_digi96.7 \
	oss_emu10k1x.7 oss_envy24.7 oss_envy24ht.7 oss_fmedia.7 \
	oss_geode.7 oss_hdaudio.7 oss_ich.7 oss_sblive.7 \
	oss_sbpci.7 oss_sbxfi.7 oss_solo.7 oss_trident.7 \
	oss_via823x.7 oss_via97.7 oss_ymf7xx.7 re_format.7 \
	pkgsrc.7

.include <bsd.man.mk>
.include <bsd.subdir.mk>
