NOOBJ=		# defined

.include <bsd.own.mk>

INCSDIR=	/usr/include/minix

INCS+= dirent.h paths.h types.h

.include "${NETBSDSRCDIR}/common/include/sys/Makefile.mount.inc"
.include "${NETBSDSRCDIR}/common/include/Makefile.termios.inc"

.include <bsd.kinc.mk>
