.include <bsd.own.mk>

INCSDIR= /usr/include/minix

INCS+=	dirent.h paths.h param.h
INCS+=	acpi.h audio_fw.h bitmap.h \
	bdev.h blockdriver.h blockdriver_mt.h \
	btrace.h \
	callnr.h chardriver.h clkconf.h com.h compiler.h \
	config.h const.h cpufeature.h crtso.h \
	debug.h devio.h devman.h dmap.h \
	driver.h drivers.h drvlib.h ds.h \
	endpoint.h fb.h fslib.h gpio.h gcov.h hash.h \
	hgfs.h i2c.h i2cdriver.h ioctl.h input.h ipc.h ipcconst.h \
	keymap.h log.h mmio.h mount.h mthread.h minlib.h \
	netdriver.h optset.h padconf.h partition.h portio.h \
	priv.h procfs.h profile.h queryparam.h \
	reboot.h rs.h safecopies.h sched.h sef.h sffs.h \
	sound.h spin.h sys_config.h sysinfo.h \
	syslib.h sysutil.h termios.h timers.h type.h \
	tty.h u64.h usb.h usb_ch9.h vbox.h \
	vboxfs.h vboxif.h vboxtype.h vm.h \
	vfsif.h vtreefs.h libminixfs.h netsock.h \
	virtio.h

.include <bsd.kinc.mk>
