#	$NetBSD: Makefile,v 1.6 2009/04/14 22:15:28 lukem Exp $
#	from: @(#)Makefile	8.1 (Berkeley) 6/6/93

PROG=	whereis
MAN=	whereis.1 which.1
LINKS=  ${BINDIR}/whereis ${BINDIR}/which

.include <bsd.prog.mk>
