.TH man 8 "14 November 2014" "1.0" "rotate man page"
.SH NAME
rotate \- rotate logs
.SH SYNOPSIS
rotate <log> <keep>
.SH DESCRIPTION
Rotate logs, where <log> is the name of the log and <keep>
is the number of copies you wish to keep
.SH EXAMPLES
rotate /var/log/syslog 1
.SH SEE ALSO

.SH AUTHOR
Manpage written by Jacob Adams <tookmund@gmail.com>
