#	$NetBSD: Makefile,v 1.71 2015/03/21 19:10:43 jmcneill Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/5/93

# missing: dump.5 plot.5

# MINIX:
MAN=	\
	\
	\
	hosts.5 ifconfig.if.5 \
	locale.alias.5 \
	\
	\
	\
	nsswitch.conf.5 \
	rc.conf.5 \
	resolv.conf.5 route.conf.5 \
	\
	\
	

#MLINKS+=capfile.5 termcap.5	
#MLINKS+=daily.5 daily.conf.5
#MLINKS+=fs.5 inode.5
#MLINKS+=hosts.equiv.5 rhosts.5
#MLINKS+=monthly.5 monthly.conf.5
MLINKS+=resolv.conf.5 resolver.5
#MLINKS+=utmp.5 wtmp.5 utmp.5 lastlog.5 passwd.5 master.passwd.5
#MLINKS+=utmpx.5 wtmpx.5 utmpx.5 lastlogx.5
#MLINKS+=weekly.5 weekly.conf.5

.include <bsd.man.mk>
.include <bsd.subdir.mk>
