#	$NetBSD: Makefile,v 1.5 2005/12/11 12:24:54 christos Exp $

INCSDIR= /usr/include/net80211

INCS=	_ieee80211.h ieee80211.h \
	ieee80211_crypto.h ieee80211_ioctl.h ieee80211_netbsd.h \
	\
	

.include <bsd.kinc.mk>
