#	$NetBSD: Makefile,v 1.13 2006/09/11 22:24:09 dbj Exp $

.include <minix.own.mk>

LIB=		l
SRCS=		libmain.c libyywrap.c

LINKS=		${LIBDIR}/libl.a ${LIBDIR}/libfl.a

.PATH:		${MINIXSRCDIR}/commands/lex

.include <minix.lib.mk>
