#!/bin/sh
#	$NetBSD: checkoldver,v 1.3 2008/04/30 13:10:50 martin Exp $
#
# Copyright (c) 2002 The NetBSD Foundation, Inc.
# All rights reserved.
#
# This code is derived from software contributed to The NetBSD Foundation
# by Christos Zoulas.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
# ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# checkoldver [dir ...]
#
# Looks in the given directories for old shared libraries and lists them
# Useful for: 'checkoldver /usr/lib | xargs rm -f'

delete() {
	obsol="$1.so"
	if [ ! -z "$2" ]
	then
		obsol="$obsol.$2"
	fi
	if [ ! -z "$3" ]
	then
		obsol="$obsol.$3"
	fi
	if [ ! -z "$4" ]
	then
		obsol="$obsol.$4"
	fi
	echo $PWD/$obsol
}

comparelib() {
	OIFS="$IFS"
	IFS="$IFS."
	set -- $1
	IFS="$OIFS"
	if [ "$3" = "[0-9]*" ]
	then
		return
	fi

	if [ -z "$libmajor" ]
	then
		libname="$1"
		libmajor="$3"
		libminor="$4"
		libtiny="$5"
		return
	fi
	if [ "$libmajor" -lt "$3" ]
	then
		delete "$libname" "$libmajor" "$libminor" "$libtiny"
		libmajor="$3"
		libminor="$4"
		libtiny="$5"
		return
	elif [ "$3" -lt "$libmajor" ]
	then
		delete "$libname" "$3" "$4" "$5"
		return
	fi

	if [ -z "$libminor" ]
	then
		return
	fi
	if [ "$libminor" -lt "$4" ]
	then
		delete "$libname" "$libmajor" "$libminor" "$libtiny"
		libmajor="$3"
		libminor="$4"
		libtiny="$5"
		return
	elif [ "$4" -lt "$libminor" ]
	then
		delete "$libname" "$3" "$4" "$5"
		return
	fi

	if [ -z "$libtiny" ]
	then
		return
	fi
	if [ "$libtiny" -lt "$5" ]
	then
		delete "$libname" "$libmajor" "$libminor" "$libtiny"
		libmajor="$3"
		libminor="$4"
		libtiny="$5"
		return
	elif [ "$5" -lt "$libminor" ]
	then
		delete "$libname" "$3" "$4" "$5"
		return
	fi
}

processonedir() {
	cd "$1"
	for lib in lib*.so
	do
		lib="${lib#lib}"
		lib="${lib%.so}"

		libmajor=
		libminor=
		libtiny=
		for link in lib$lib.so.[0-9]*.[0-9]*.[0-9]*
		do
			comparelib "$link"
		done

		libmajor=
		libminor=
		libtiny=
		for link in lib$lib.so.[0-9]*.[0-9]*
		do
			comparelib "$link"
		done

		libmajor=
		libminor=
		libtiny=
		for link in lib$lib.so.[0-9]*
		do
			comparelib "$link"
		done
	done
}

for i
do
	processonedir "$i"
done
