${ASM}:
	${_MKTARGET_CREATE}
	printf '/* MINIX3 */							\n\
/* 										\n\
* Compatibility jump table for renamed symbols. 				\n\
*										\n\
* DO NOT EDIT: this file is automatically generated.				\n\
*/										\n\
#include <machine/asm.h>							\n\
.global ${.PREFIX:S/^compat__//:C/([0-9]{2})$//};				\n\
.global ${.PREFIX:S/^compat//};							\n\
.type ${.PREFIX:S/^compat__//:C/([0-9]{2})$//},@function			\n\
${.PREFIX:S/^compat__//:C/([0-9]{2})$//}:					\n\
#ifdef PIC									\n\
jmpl *PIC_PLT(${.PREFIX:S/^compat//})						\n\
#else										\n\
jmp ${.PREFIX:S/^compat//}							\n\
#endif										\n\
\n ' >${.TARGET}

