.include <bsd.own.mk>

.if ${MACHINE_ARCH} == "earm"
SUBDIR+=	eepromread
.endif # ${MACHINE_ARCH} == "earm"

SUBDIR+=	grep
SUBDIR+=	ministat
SUBDIR+=	top
SUBDIR+=	toproto
SUBDIR+=	trace

.include <bsd.subdir.mk>
