#	$NetBSD: Makefile.inc,v 1.3 2009/08/14 19:23:55 dsl Exp $
#
#	There are likely more that we will notice when we go native

NO_SRCS+= imax.c imin.c lmax.c lmin.c max.c min.c ulmax.c ulmin.c
NO_SRCS+= __main.c strlen.c strcmp.c
