
INCSDIR= /usr/include/sys

# Minix specific system headers
INCS=	elf64.h elf_common.h elf_core.h elf_generic.h \
	ioc_block.h ioc_disk.h ioc_fb.h ioc_fbd.h ioc_file.h ioc_memory.h \
	ioc_net.h ioc_sound.h ioc_tape.h \
	kbdio.h \
	procfs.h statfs.h svrctl.h video.h vm.h 

.include <bsd.kinc.mk>
