#	$NetBSD: Makefile,v 1.41 2012/11/05 00:57:42 alnsn Exp $

INCSDIR= /usr/include/i386

INCS=	ansi.h asm.h \
	bootinfo.h bswap.h byte_swap.h \
	cdefs.h cpu.h \
	disklabel.h \
	elf_machdep.h endian.h endian_machdep.h \
	fenv.h float.h frame.h  \
	\
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	\
	\
	\
	limits.h lock.h \
	math.h mcontext.h mutex.h multiboot.h \
	npx.h \
	param.h pcb.h pio.h proc.h profile.h \
	ptrace.h \
	rwlock.h \
	segments.h setjmp.h signal.h \
	sysarch.h \
	trap.h tss.h types.h \
	vmparam.h \
	wchar_limits.h

.include <bsd.kinc.mk>
