#	$NetBSD: Makefile,v 1.40 2012/08/08 18:37:52 drochner Exp $

INCSDIR= /usr/include/i386

INCS=	ansi.h asm.h \
	bootinfo.h bswap.h byte_swap.h \
	cdefs.h cpu.h \
	disklabel.h \
	elf_machdep.h endian.h endian_machdep.h \
	fenv.h float.h \
	\
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	\
	\
	\
	limits.h \
	math.h mcontext.h mutex.h multiboot.h \
	npx.h \
	param.h pio.h profile.h \
	\
	rwlock.h \
	setjmp.h signal.h \
	\
	types.h \
	vmparam.h \
	wchar_limits.h

.include <bsd.kinc.mk>
