#	$NetBSD: Makefile,v 1.1 2013/09/02 14:34:58 joerg Exp $

HOSTPROGNAME=	${MACHINE_GNU_PLATFORM}-lld
HOSTPROG_CXX=	${MACHINE_GNU_PLATFORM}-lld
HOST_SRCDIR=	external/bsd/llvm/bin/lld

.include "${.CURDIR}/../Makefile.host"
