# $NetBSD: Makefile,v 1.3 2011/06/11 18:03:19 christos Exp $
#
.include "Makefile.inc"
.include <bsd.own.mk>

#LSC: Unsupported on MINIX
#TESTS_SUBDIRS=		ld.elf_so

TESTSDIR=	${TESTSBASE}/libexec

.include <bsd.test.mk>
