.TH UDS 4
.SH NAME
uds \- unix domain sockets device
.SH DESCRIPTION
The \fIuds\fP device gives access to the unix domain socket services in 
Minix. It is a virtual device similar to the \fItcp\fP and \fIudp\fP 
Internet Protocol server devices.
.SH SEE ALSO
.BR socket(2),
.BR socketpair(2),
.BR dev(4),
.BR ip(4),
.BR unix(8)
.SH HISTORY
This device first appeared in Minix 3.1.8.
