#	$NetBSD: Makefile,v 1.36 2007/12/20 23:46:12 ad Exp $
.include <bsd.own.mk>

INCSDIR= /usr/include/i386

INCS= 	ansi.h asm.h bswap.h byte_swap.h cdefs.h \
	endian.h endian_machdep.h fenv.h float.h ieee.h \
	ieeefp.h int_const.h int_fmtio.h int_limits.h \
	int_mwgwtypes.h int_types.h limits.h \
	math.h mcontext.h npx.h param.h profile.h \
	setjmp.h signal.h stdarg.h types.h \
	vmparam.h wchar_limits.h \
	archconst.h archtypes.h bios.h cmos.h cpu.h diskparm.h fpu.h int86.h \
	interrupt.h memory.h multiboot.h partition.h \
	pci.h pci_amd.h pci_intel.h pci_sis.h pci_via.h \
	ports.h stackframe.h vm.h elf.h elf_machdep.h mutex.h \
	disklabel.h ipcconst.h


.include <bsd.kinc.mk>
