#	$NetBSD: Makefile,v 1.4 2001/04/11 19:07:38 jdolecek Exp $

INCSDIR= /usr/include/dev/wscons

# Only install includes which are used by userland
INCS=	wsconsio.h wsdisplay_usl_io.h wsksymdef.h wsksymdef.h wsksymvar.h

.include <bsd.kinc.mk>
