PROG=	cp
BINDIR=	/bin
MAN=

LINKS+=      ${BINDIR}/cp ${BINDIR}/rm
LINKS+=      ${BINDIR}/cp ${BINDIR}/mv
LINKS+=      ${BINDIR}/cp ${BINDIR}/ln
LINKS+=      ${BINDIR}/cp ${BINDIR}/clone
LINKS+=      ${BINDIR}/cp ${BINDIR}/cpdir

.include <bsd.prog.mk>
