# $NetBSD: Makefile,v 1.1 2012/03/17 16:33:14 jruoho Exp $

NOMAN=			# defined

.include <bsd.own.mk>

TESTSDIR=		${TESTSBASE}/usr.bin/make

TESTS_SH=		t_make

FILESDIR=		${TESTSDIR}
FILES=			d_comment.mk
FILES+=			d_comment.out
FILES+=			d_cond1.mk
FILES+=			d_cond1.out
FILES+=			d_dotwait.mk
FILES+=			d_dotwait.out
FILES+=			d_export.mk
FILES+=			d_export.out
FILES+=			d_export_all.mk
FILES+=			d_export_all.out
FILES+=			d_moderrs.mk
FILES+=			d_moderrs.out
FILES+=			d_modmatch.mk
FILES+=			d_modmatch.out
FILES+=			d_modmisc.mk
FILES+=			d_modmisc.out
FILES+=			d_modorder.mk
FILES+=			d_modorder.out
FILES+=			d_modts.mk
FILES+=			d_modts.out
FILES+=			d_modword.mk
FILES+=			d_modword.out
FILES+=			d_posix.mk
FILES+=			d_posix.out
FILES+=			d_qequals.mk
FILES+=			d_qequals.out
FILES+=			d_ternary.mk
FILES+=			d_ternary.out
FILES+=			d_unmatchedvarparen.mk
FILES+=			d_unmatchedvarparen.out
FILES+=			d_varcmd.mk
FILES+=			d_varcmd.out

.include <bsd.test.mk>
