#	$NetBSD: Makefile,v 1.4 2014/08/10 08:53:22 hannken Exp $
#

.PATH:  ${.CURDIR}/../../../../fs/hfs

LIB=	rumpfs_hfs

SRCS=	hfs_subr.c hfs_vfsops.c hfs_vnops.c libhfs.c unicode.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
