/* Automatically generated file; do not edit */
#include <sys/cdefs.h>
__RCSID("$NetBSD: errlist.awk,v 1.4 2010/12/16 22:52:32 joerg Exp $");
#include <errno.h>
static const char *const errlist[] = {
	[0] = "Undefined error: 0",			/* 0 - ENOERROR */
	[99] = "generic error",			/* 99 - EGENERIC */
	[1] = "operation not permitted",		/* 1 - EPERM */
	[2] = "no such file or directory",		/* 2 - ENOENT */
	[3] = "no such process",			/* 3 - ESRCH */
	[4] = "interrupted function call",		/* 4 - EINTR */
	[5] = "input/output error",			/* 5 - EIO */
	[6] = "no such device or address",		/* 6 - ENXIO */
	[7] = "arg list too long",			/* 7 - E2BIG */
	[8] = "exec format error",			/* 8 - ENOEXEC */
	[9] = "bad file descriptor",			/* 9 - EBADF */
	[10] = "no child process",			/* 10 - ECHILD */
	[11] = "resource temporarily unavailable",	/* 11 - EAGAIN */
	[12] = "not enough space",			/* 12 - ENOMEM */
	[13] = "permission denied",			/* 13 - EACCES */
	[14] = "bad address",				/* 14 - EFAULT */
	[15] = "Extension: not a block special file",	/* 15 - ENOTBLK */
	[16] = "resource busy",			/* 16 - EBUSY */
	[17] = "file exists",				/* 17 - EEXIST */
	[18] = "improper link",			/* 18 - EXDEV */
	[19] = "no such device",			/* 19 - ENODEV */
	[20] = "not a directory",			/* 20 - ENOTDIR */
	[21] = "is a directory",			/* 21 - EISDIR */
	[22] = "invalid argument",			/* 22 - EINVAL */
	[23] = "too many open files in system",	/* 23 - ENFILE */
	[24] = "too many open files",			/* 24 - EMFILE */
	[25] = "inappropriate I/O control operation",	/* 25 - ENOTTY */
	[26] = "no longer used",			/* 26 - ETXTBSY */
	[27] = "file too large",			/* 27 - EFBIG */
	[28] = "no space left on device",		/* 28 - ENOSPC */
	[29] = "invalid seek",				/* 29 - ESPIPE */
	[30] = "read-only file system",		/* 30 - EROFS */
	[31] = "too many links",			/* 31 - EMLINK */
	[32] = "broken pipe",				/* 32 - EPIPE */
	[33] = "domain error    	(from ANSI C std )",	/* 33 - EDOM */
	[34] = "result too large	(from ANSI C std )",	/* 34 - ERANGE */
	[35] = "resource deadlock avoided",		/* 35 - EDEADLK */
	[36] = "file name too long",			/* 36 - ENAMETOOLONG */
	[37] = "no locks available",			/* 37 - ENOLCK */
	[38] = "function not implemented",		/* 38 - ENOSYS */
	[39] = "directory not empty",			/* 39 - ENOTEMPTY */
	[40] = "too many levels of symlinks detected",	/* 40 - ELOOP */
	[41] = "service restarted",			/* 41 - ERESTART */
	[43] = "Identifier removed",			/* 43 - EIDRM */
	[44] = "illegal byte sequence",		/* 44 - EILSEQ */
	[45] = "No message of desired type",		/* 45 - ENOMSG */
	[46] = "Value too large to be stored in data type",/* 46 - EOVERFLOW */
	[50] = "invalid packet size for some protocol",/* 50 - EPACKSIZE */
	[51] = "not enough buffers left",		/* 51 - ENOBUFS */
	[52] = "illegal ioctl for device",		/* 52 - EBADIOCTL */
	[53] = "badmode in ioctl",			/* 53 - EBADMODE */
	[54] = "call would block on nonblocking socket",/* 54 - EWOULDBLOCK */
	[55] = "network unreachable",			/* 55 - ENETUNREACH */
	[56] = "host unreachable",			/* 56 - EHOSTUNREACH */
	[57] = "already connected",			/* 57 - EISCONN */
	[58] = "address in use",			/* 58 - EADDRINUSE */
	[59] = "connection refused",			/* 59 - ECONNREFUSED */
	[60] = "connection reset",			/* 60 - ECONNRESET */
	[61] = "connection timed out",			/* 61 - ETIMEDOUT */
	[62] = "urgent data present",			/* 62 - EURG */
	[63] = "no urgent data present",		/* 63 - ENOURG */
	[64] = "no connection (yet or anymore )",	/* 64 - ENOTCONN */
	[65] = "a write call to a shutdown connection",/* 65 - ESHUTDOWN */
	[66] = "no such connection",			/* 66 - ENOCONN */
	[67] = "address family not supported",		/* 67 - EAFNOSUPPORT */
	[68] = "protocol not supported by AF",		/* 68 - EPROTONOSUPPORT */
	[69] = "Protocol wrong type for socket",	/* 69 - EPROTOTYPE */
	[70] = "Operation now in progress",		/* 70 - EINPROGRESS */
	[71] = "Can't assign requested address",	/* 71 - EADDRNOTAVAIL */
	[72] = "Connection already in progress",	/* 72 - EALREADY */
	[73] = "Message too long",			/* 73 - EMSGSIZE */
	[74] = "Socket operation on non-socket",	/* 74 - ENOTSOCK */
	[75] = "Protocol not available",		/* 75 - ENOPROTOOPT */
	[76] = "Operation not supported",		/* 76 - EOPNOTSUPP */
	[77] = "network is down",			/* 77 - ENETDOWN */
	[78] = "Protocol family not supported",	/* 78 - EPFNOSUPPORT */
	[79] = "Destination address required",		/* 79 - EDESTADDRREQ */
	[80] = "Host is down",				/* 80 - EHOSTDOWN */
	[81] = "Network dropped connection on reset",	/* 81 - ENETRESET */
	[82] = "Socket type not supported",		/* 82 - ESOCKTNOSUPPORT */
	[83] = "Software caused connection abort",	/* 83 - ECONNABORTED */
	[84] = "Too many references: can't splice",	/* 84 - ETOOMANYREFS */
	[101] = "can't send message due to deadlock",	/* 101 - ELOCKED */
	[102] = "illegal system call number",		/* 102 - EBADCALL */
	[103] = "bad source or destination process",	/* 103 - EBADSRCDST */
	[104] = "no permission for system call",	/* 104 - ECALLDENIED */
	[105] = "source or destination is not alive",	/* 105 - EDEADSRCDST */
	[106] = "source or destination is not ready",	/* 106 - ENOTREADY */
	[107] = "destination cannot handle request",	/* 107 - EBADREQUEST */
	[110] = "IPC trap not allowed",			/* 110 - ETRAPDENIED */
	[201] = "pseudo-code: don't send a reply",	/* 201 - EDONTREPLY */
	[150] = "Inappropriate file type or format",	/* 150 - EFTYPE */
	[151] = "Authentication error",			/* 151 - EAUTH */
	[152] = "Need authenticator",			/* 152 - ENEEDAUTH */
	[153] = "Operation canceled",			/* 153 - ECANCELED */
	[160] = "Stale NFS file handle",		/* 160 - ESTALE */
	[161] = "Too many levels of remote in path",	/* 161 - EREMOTE */
	[162] = "RPC struct is bad",			/* 162 - EBADRPC */
	[163] = "RPC version wrong",			/* 163 - ERPCMISMATCH */
	[164] = "RPC prog. not avail",			/* 164 - EPROGUNAVAIL */
	[165] = "Program version wrong",		/* 165 - EPROGMISMATCH */
	[166] = "Bad procedure for program",		/* 166 - EPROCUNAVAIL */
	[170] = "Bad or Corrupt message",		/* 170 - EBADMSG */
	[175] = "Too many processes",			/* 175 - EPROCLIM */
	[176] = "Too many users",			/* 176 - EUSERS */
	[177] = "Disc quota exceeded",			/* 177 - EDQUOT */
	[180] = "Multihop attempted ",			/* 180 - EMULTIHOP */
	[181] = "Link has been severed",		/* 181 - ENOLINK */
	[182] = "Protocol error",			/* 182 - EPROTO */
	[185] = "Attribute not found",			/* 185 - ENOATTR */
	[190] = "No message available",			/* 190 - ENODATA */
	[191] = "No STREAM resources",			/* 191 - ENOSR */
	[192] = "Not a STREAM",				/* 192 - ENOSTR */
	[193] = "STREAM ioctl timeout",			/* 193 - ETIME */
	[301] = "specified endpoint is bad",		/* 301 - EBADEPT */
	[302] = "specified endpoint is not alive",	/* 302 - EDEADEPT */
};

const int sys_nerr = sizeof(errlist) / sizeof(errlist[0]);
const char * const *sys_errlist = errlist;
