
LIB=	install
SRCS=	automatic.c conflicts.c dewey.c fexec.c file.c \
	gpgsig.c global.c iterate.c license.c lpkg.c opattern.c \
	parse-config.c pkgdb.c plist.c remove.c \
	str.c var.c version.c vulnerabilities-file.c xwrapper.c \
	pkg_io.c pkg_signature.c

.include "../Makefile.inc"

LIBISPRIVATE=	1
.include <bsd.lib.mk>
