.TH man 8 "14 November 2014" "1.0" "update_bootcfg  man page"
.SH NAME
update_bootcfg \- Update /boot.cfg

.SH SYNOPSIS
update_bootcfg

.SH DESCRIPTION
Updates /boot.cfg from /etc/boot.cfg.default and /etc/boot.cfg.local

.SH EXAMPLES
update_bootcfg

.SH SEE ALSO
boot.cfg(5)

.SH AUTHOR
Manpage written by Jacob Adams <tookmund@gmail.com>
