#	$NetBSD: Makefile,v 1.2 2002/09/18 07:50:31 lukem Exp $

NOOBJ=	# defined

.include <bsd.own.mk>

.if ${MKNLS} != "no"
FILES=	nls.alias
FILESDIR=/usr/share/nls # XXX use NLSDIR?

.include <bsd.prog.mk>
.endif
