#	$NetBSD: Makefile,v 1.5 2009/01/02 00:20:21 tnozaki Exp $

.include <bsd.own.mk>

NOOBJ=	# defined
NOMAN=	# defined

SUBDIR=	ctype monetary numeric time messages

FILES=		locale.alias
FILESOWN=	${LOCALEOWN}
FILESGRP=	${LOCALEGRP}
FILESMODE=	${LOCALEMODE}
FILESDIR=	${LOCALEDIR}

.include <bsd.prog.mk>
.include <bsd.subdir.mk>
