.\"	$NetBSD: _lwp_wakeup.2,v 1.5 2008/04/30 13:10:51 martin Exp $
.\"
.\" Copyright (c) 2003 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Jason R. Thorpe of Wasabi Systems, Inc.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd January 13, 2003
.Dt _LWP_WAKEUP 2
.Os
.Sh NAME
.Nm _lwp_wakeup
.Nd make a blocked light-weight process runnable
.Sh LIBRARY
.Lb libc
.Sh SYNOPSIS
.In lwp.h
.Ft int
.Fn _lwp_wakeup "lwpid_t lwp"
.Sh DESCRIPTION
.Fn _lwp_wakeup
makes a blocked LWP runnable.  The blocked LWP must be in
.Dv LSSLEEP
state.
Unblocking the LWP does not guarantee that it will make progress; it
may block again as soon as it resumes execution in the kernel.
.Sh RETURN VALUES
Upon successful completion,
.Fn _lwp_wakeup
returns a value of 0.
Otherwise, an error code is returned to indicate the error.
.Sh ERRORS
.Fn _lwp_wakeup
will fail if:
.Bl -tag -width [ENODEV]
.It Bq Er ESRCH
No LWP can be found in the current process corresponding to that
specified by
.Fa lwp .
.It Bq Er ENODEV
The specified LWP is not in
.Dv LSSLEEP
state.
.It Bq Er EBUSY
The specified LWP is blocked in an uninterruptible sleep.
.El
.Sh HISTORY
The
.Fn _lwp_wakeup
system call first appeared in
.Nx 2.0 .
