.\"	$NetBSD: _lwp_getprivate.2,v 1.4 2008/04/30 13:10:51 martin Exp $
.\"
.\" Copyright (c) 2003 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Jason R. Thorpe of Wasabi Systems, Inc.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd January 16, 2003
.Dt _LWP_GETPRIVATE 2
.Os
.Sh NAME
.Nm _lwp_getprivate ,
.Nm _lwp_setprivate
.Nd get and set light-weight process private data
.Sh LIBRARY
.Lb libc
.Sh SYNOPSIS
.In lwp.h
.Ft void *
.Fn _lwp_getprivate void
.Ft void
.Fn _lwp_setprivate "void *ptr"
.Sh DESCRIPTION
.Fn _lwp_setprivate
stores the pointer to private data
.Fa ptr
in a location private to the LWP.
.Pp
.Fn _lwp_getprivate
returns the pointer to private data for the LWP.
.Sh ERRORS
The
.Fn _lwp_getprivate
and
.Fn _lwp_setprivate
functions are always successful, and no return value is reserved to indicate
an error.
.Sh SEE ALSO
.Xr _lwp_makecontext 3
.Sh HISTORY
The
.Fn _lwp_getprivate
and
.Fn _lwp_setprivate
system calls first appeared in
.Nx 2.0 .
