# Makefile for commands.

.include <bsd.own.mk>

SUBDIR=	add_route arp at backup btrace \
	cawf cdprobe \
	ci cleantmp cmp co \
	compress crc cron crontab \
	dd decomp16 DESCRIBE devmand devsize dhcpd \
	dhrystone diff diskctl \
	eject fbdctl \
	find fix format fsck.mfs \
	gcov-pull grep host \
	hostaddr ifconfig ifdef \
	intr ipcrm ipcs irdpd isoread \
	loadkeys loadramdisk logger look lp \
	lpd lspci mail MAKEDEV \
	mined \
	mount mt netconf \
	nonamed \
	postinstall prep printroot \
	profile progressbar pr_routes ps pwdauth \
	ramdisk rarpd rawspeed rcp readclock \
	remsync rget rlogin \
	rotate rsh rshd service setup \
	slip spell sprofalyze sprofdiff srccrc \
	svclog svrctl swifi synctree sysenv \
	syslogd tcpd tcpdp tcpstat telnet \
	telnetd term termcap tget time \
	truncate udpstat umount \
	update version vol \
	writeisofs fetch \
	zdump zmodem pkgin_cd pkgin_all pkgin_sets \
	worldstone updateboot update_bootcfg \
	atnormalize dosread fdisk loadfont \
	autopart part partition playwave  \
	recwave repartition screendump

.include <bsd.subdir.mk>
