# Makefile for commands.

.include <bsd.own.mk>

SUBDIR=	at backup \
	cawf cdprobe \
	cleantmp \
	compress crc cron crontab \
	DESCRIBE devmand devsize \
	dhrystone \
	eject \
	fix format fsck.mfs \
	gcov-pull \
	ifdef \
	intr isoread \
	loadkeys loadramdisk look lp \
	lpd lspci mail MAKEDEV \
	minix-service mount mt netconf \
	prep printroot \
	profile progressbar \
	ramdisk rawspeed readclock \
	remsync \
	rotate setup \
	slip spell sprofalyze sprofdiff srccrc \
	svrctl swifi synctree sysenv \
	term termcap tget \
	truncate umount \
	update version vol \
	writeisofs fetch \
	zmodem pkgin_cd pkgin_all pkgin_sets \
	worldstone updateboot update_asr update_bootcfg \
	atnormalize dosread fdisk loadfont \
	autopart part partition playwave  \
	recwave repartition screendump

.include <bsd.subdir.mk>
