.TH NETCONF 8
.SH NAME
netconf - a script to configure the network
.SH SYNOPSIS
.B netconf 
.RB [\-q]
.RB [\-p 
.RI <prefix>]
.RB [\-e 
.RI <num>] 
.RB [\-a]

.B netconf
.RB [\-H
.RI <hostname>
.RB ]
.RB \-i
.RI <ip> 
.RB \-n 
.RI <mask>
.RB \-g
.RI <gw>
.RB \-d
.RI "<prim dns>"
.RB [\-s
.RI  "<sec dns> ]"

.B netconf
.RB [\-c]

.SH DESCRIPTION
.B Netconf
allows the root user to configure the network.  It defaults to an interactive 
mode.  However, command line options can be used to answer some of the 
questions. 
.SH OPTIONS
.TP
.B \-q
Limit generated output
.TP
.B \-p
Path prefix for configuration files. 
.TP
.B \-e
Ethernet card
.TP
.B \-a
Use DHCP.  (Will override -H, -i, -n, -g, -d, and -s flags)
.TP
.B \-H
Hostname
.TP
.B \-i
IP address
.TP
.B \-n
Netmask
.TP
.B \-g
Default Gateway
.TP
.B \-d
Primary DNS
.TP
.B \-s
Secondary DNS
.TP
.B \-h
Usage
.TP
.B \-c
Prints list of supported ethernet cards
.SH "SEE ALSO"
ifconfig(8), 
dhcpd(8)
.SH NOTES
Must be the root user to execute this script.
.SH AUTHOR
Leith Brandeland <lb.minix@gmail.com>
