#define KW_SERVICE	"service"
#define KW_UID		"uid"
#define KW_SELF		"SELF"
#define KW_SIGMGR	"sigmgr"
#define KW_SCHEDULER	"scheduler"
#define KW_PRIORITY	"priority"
#define KW_QUANTUM	"quantum"
#define KW_CPU		"cpu"
#define KW_IRQ		"irq"
#define KW_IO		"io"
#define KW_PCI		"pci"
#define KW_DEVICE	"device"
#define KW_CLASS	"class"
#define KW_SYSTEM	"system"
#define KW_IPC		"ipc"
#define KW_VM		"vm"
#define KW_CONTROL	"control"
#define KW_ALL		"ALL"
#define KW_ALL_SYS	"ALL_SYS"
#define KW_NONE		"NONE"
#define KW_BASIC	"BASIC"
#define KW_TYPE		"type"	/* set service type */
#define KW_NET		"net"	/* ethernet driver type */
#define KW_DESCR	"descr"	/* human-readable string */
#define KW_DOMAIN	"domain"	/* socket domain (protocol family) */
