.TH man 8 "9 May 2015" "1.0" "sprofdiff man page"
.SH NAME
sprofdiff \- compare multiple sprofile traces
.SH SYNOPSIS
sprofdiff leftfile [-r] rightfile
.SH DESCRIPTION
sprofdiff compares the sprofile information from multiple output files of 'sprofalyze -d'.
.SH OPTIONS
.IP -r
When comparing multiple files, use this option to keep them separate.
.SH SEE ALSO
.B sprofalyze(8)
.SH AUTHOR
Manpage written by Jacob Adams <tookmund@gmail.com>
