.TH LP 4
.SH NAME
lp \- line printer
.SH DESCRIPTION
The
.B lp
device refers to the line printer attached to the parallel port.  Any byte
written to this device is printed.  Only one process may have the device
open.
.PP
The
.B write (2)
call may return with a smaller count then the number of bytes requested to
write.  The next write call is then likely to fail with the error code
.B EAGAIN
if the printer is out of paper, or
.B EIO
if the printer is turned off.
.SH FILES
.TP 10
/dev/lp
Parallel port device.
.SH "SEE ALSO"
.BR lp (1).
.SH BUGS
Only one parallel port is supported.
.SH AUTHOR
Kees J. Bot (kjb@cs.vu.nl)
