MAN=	console.4 controller.4 dev.4 fd.4 ip.4 lp.4 mtio.4 tty.4 uds.4

MLINKS += console.4 keyboard.4
MLINKS += controller.4 disk.4
MLINKS += controller.4 tape.4
MLINKS += controller.4 at.4
MLINKS += controller.4 bios.4
MLINKS += controller.4 esdi.4
MLINKS += controller.4 aha1540.4
MLINKS += controller.4 ncr810.4
MLINKS += controller.4 dosfile.4
MLINKS += ip.4 eth.4
MLINKS += ip.4 psip.4
MLINKS += ip.4 udp.4

.include <bsd.man.mk>
