$ $NetBSD: ja_JP.UTF-8.msg,v 1.2 2011/04/18 22:46:48 joerg Exp $
$ $FreeBSD: head/usr.bin/grep/nls/ja_JP.UTF-8.msg 210622 2010-07-29 18:02:57Z gabor $
$
$set 1
$quote "
1 "(標準入力)"
2 "bzip2 圧縮ファイルを読み込むことができません"
3 "%s オプションの指定値に誤りがあります"
4 "使い方: %s [-abcDEFGHhIiJLlmnOoPqRSsUVvwxZz] [-A 数字] [-B 数字] [-C[数字]]\n"
5 "\t[-e パターン] [-f ファイル名] [--binary-files=値] [--color=値]\n"
6 "\t[--context[=数字]] [--directories=動作] [--label] [--line-buffered]\n"
7 "\t[パターン] [ファイル名 ...]\n"
8 "バイナリファイル %s にマッチしました\n"
9 "%s (BSD grep) %s\n"
