$ $NetBSD: ru_RU.KOI8-R.msg,v 1.2 2011/04/18 22:46:48 joerg Exp $
$ $FreeBSD: head/usr.bin/grep/nls/ru_RU.KOI8-R.msg 210622 2010-07-29 18:02:57Z gabor $
$
$set 1
$quote "
1 "(стандартный ввод)"
2 "не могу прочитать сжатый в bzip2 файл"
3 "неизвестный ключ %s"
4 "использование: %s [-abcDEFGHhIiJLlmnOoPqRSsUVvwxZz] [-A чис] [-B чис] [-C[чис]]\n"
5 "\t[-e шаблон] [-f файл] [--binary-files=значение] [--color=когда]\n"
6 "\t[--context[=чис]] [--directories=действие] [--label] [--line-buffered]\n"
7 "\t[шаблон] [файл ...]\n"
8 "двоичный файл %s совпадает\n"
9 "%s (BSD grep) %s\n"
