$ $NetBSD: uk_UA.UTF-8.msg,v 1.2 2011/04/18 22:46:48 joerg Exp $
$ $FreeBSD: head/usr.bin/grep/nls/uk_UA.UTF-8.msg 210927 2010-08-06 10:34:48Z gabor $
$set 1
$quote "
1 "(стандартний ввід)"
2 "не можу прочитати стиснутий bzip2 файл"
3 "невiдома опція %s"
4 "використання: %s [-abcDEFGHhIiJLlmnOoPqRSsUVvwxZz] [-A чис] [-B чис] [-C[чис]]\n"
5 "\t[-e шаблон] [-f файл] [--binary-files=значення] [--color=коли]\n"
6 "\t[--context[=чис] [--directories=дія] [--label] [--line-buffered]\n"
7 "\t[шаблон] [файл ...]\n"
8 "двійковий файл %s співпадає\n"
9 "%s (BSD grep) %s\n"
