.global mktemp
.global mknod
.global ctime
.global difftime
.global gmtime
.global localtime
.global time
.global mktime
.global tzset
.global getitimer
.global setitimer
.global settimeofday
.global nanosleep
.global ctime_r
.global gmtime_r
.global localtime_r
.global time2posix
.global posix2time
.global timegm
.global timeoff
.global timelocal
.global offtime
.global tzsetwall
.global offtime_r
.global localtime_rz
.global ctime_rz
.global mktime_z
.global timelocal_z
.global time2posix_z
.global posix2time_z
.global tzalloc
.global tzfree
.global tzgetname
.global select
.global opendir
.global readdir
.global readdir_r
.global __opendir2
.global scandir
.global getdents
.global alphasort
.global fts_children
.global fts_close
.global fts_open
.global fts_read
.global fts_set
.global glob
.global globfree
.global dbm_delete
.global dbm_fetch
.global dbm_firstkey
.global dbm_nextkey
.global dbm_store
.global getpwuid
.global getpwnam
.global getpwnam_r
.global getpwuid_r
.global getpwent
.global getpwent_r
.global setjmp
.global longjmp
.global sigsetjmp
.global siglongjmp
.global sigaction
.global sigaddset
.global sigdelset
.global sigemptyset
.global sigfillset
.global sigismember
.global sigpending
.global sigprocmask
.global sigsuspend
.global unsetenv
.global getutent
.global getutxent
.global getutxid
.global getutxline
.global pututxline
.global updwtmpx
.global getlastlogx
.global updlastlogx
.global getutmp
.global getutmpx
.global utime
.global unvis

.global _mktemp
.global __mknod50
.global __ctime50
.global __difftime50
.global __gmtime50
.global __locatime50
.global __time50
.global __mktime50
.global __tzset50
.global __getitimer50
.global __setitimer50
.global __settimeofday50
.global __nanosleep50
.global __ctime_r50
.global __gmtime_r50
.global __localtime_r50
.global __time2posix50
.global __posix2time50
.global __timegm50
.global __timeoff50
.global __timelocal50
.global __offtime50
.global __tzsetwall50
.global __offtime_r50
.global __localtime_rz50
.global __ctime_rz50
.global __mktime_z50
.global __timelocal_z50
.global __time2posix_z50
.global __posix2time_z50
.global __tzalloc50
.global __tzfree50
.global __tzgetname50
.global __select50
.global __opendir30
.global __readdir30
.global __readdir_r30
.global __opendir230
.global __scandir30
.global __getdents30
.global __alphasort30
.global __fts_children60
.global __fts_close60
.global __fts_open60
.global __fts_read60
.global __fts_set60
.global __glob30
.global __globfree30
.global __dbm_delete13
.global __dbm_fetch13
.global __dbm_firstkey13
.global __dbm_nextkey13
.global __dbm_store13
.global __getpwuid50
.global __getpwnam50
.global __getpwnam_r50
.global __getpwuid_r50
.global __getpwent50
.global __getpwent_r50
.global __setjmp14
.global __longjmp14
.global __sigsetjmp14
.global __siglongjmp14
.global __sigaction14
.global __sigaddset14
.global __sigdelset14
.global __sigemptyset14
.global __sigfillset14
.global __sigismember14
.global __sigpending14
.global __sigprocmask14
.global __sigsuspend14
.global __unsetenv13
.global __getutent50
.global __getutxent50
.global __getutxid50
.global __getutxline50
.global __pututxline50
.global __updwtmpx50
.global __getlastlogx50
.global __updlastlogx50
.global __getutmp50
.global __getutmpx50
.global __utime50
.global __unvis13

mknod: jmp __mknod50
ctime: jmp __ctime50
difftime: jmp __difftime50
gmtime: jmp __gmtime50
localtime: jmp __locatime50
time: jmp __time50
mktime: jmp __mktime50
tzset: jmp __tzset50
getitimer: jmp __getitimer50
setitimer: jmp __setitimer50
settimeofday: jmp __settimeofday50
nanosleep: jmp __nanosleep50
ctime_r: jmp __ctime_r50
gmtime_r: jmp __gmtime_r50
localtime_r: jmp __localtime_r50
time2posix: jmp __time2posix50
posix2time: jmp __posix2time50
timegm: jmp __timegm50
timeoff: jmp __timeoff50
timelocal: jmp __timelocal50
offtime: jmp __offtime50
tzsetwall: jmp __tzsetwall50
offtime_r: jmp __offtime_r50
localtime_rz: jmp __localtime_rz50
ctime_rz: jmp __ctime_rz50
mktime_z: jmp __mktime_z50
timelocal_z: jmp __timelocal_z50
time2posix_z: jmp __time2posix_z50
posix2time_z: jmp __posix2time_z50
tzalloc: jmp __tzalloc50
tzfree: jmp __tzfree50
tzgetname: jmp __tzgetname50
select: jmp __select50
opendir: jmp __opendir30
readdir: jmp __readdir30
readdir_r: jmp __readdir_r30
__opendir2: jmp __opendir230
scandir: jmp __scandir30
getdents: jmp __getdents30
alphasort: jmp __alphasort30
fts_children: jmp __fts_children60
fts_close: jmp __fts_close60
fts_open: jmp __fts_open60
fts_read: jmp __fts_read60
fts_set: jmp __fts_set60
glob: jmp __glob30
globfree: jmp __globfree30
dbm_delete: jmp __dbm_delete13
dbm_fetch: jmp __dbm_fetch13
dbm_firstkey: jmp __dbm_firstkey13
dbm_nextkey: jmp __dbm_nextkey13
dbm_store: jmp __dbm_store13
getpwuid: jmp __getpwuid50
getpwnam: jmp __getpwnam50
getpwnam_r: jmp __getpwnam_r50
getpwuid_r: jmp __getpwuid_r50
getpwent: jmp __getpwent50
getpwent_r: jmp __getpwent_r50
setjmp: jmp __setjmp14
longjmp: jmp __longjmp14
sigsetjmp: jmp __sigsetjmp14
siglongjmp: jmp __siglongjmp14
sigaction: jmp __sigaction14
sigaddset: jmp __sigaddset14
sigdelset: jmp __sigdelset14
sigemptyset: jmp __sigemptyset14
sigfillset: jmp __sigfillset14
sigismember: jmp __sigismember14
sigpending: jmp __sigpending14
sigprocmask: jmp __sigprocmask14
sigsuspend: jmp __sigsuspend14
unsetenv: jmp __unsetenv13
getutent: jmp __getutent50
getutxent: jmp __getutxent50
getutxid: jmp __getutxid50
getutxline: jmp __getutxline50
pututxline: jmp __pututxline50
updwtmpx: jmp __updwtmpx50
getlastlogx: jmp __getlastlogx50
updlastlogx: jmp __updlastlogx50
getutmp: jmp __getutmp50
getutmpx: jmp __getutmpx50
utime: jmp __utime50
unvis: jmp __unvis13
mktemp: jmp _mktemp
