#	$NetBSD: Makefile,v 1.3 2006/10/29 06:17:08 dogcow Exp $

HOSTPROGNAME=	${_TOOL_PREFIX}cksum
HOST_SRCDIR=	usr.bin/cksum
CPPFLAGS+= 	-I${.CURDIR}/../compat/sys

.include "${.CURDIR}/../Makefile.host"
