.\"	$NetBSD: curses_keyname.3,v 1.5 2008/04/30 13:10:51 martin Exp $
.\" Copyright (c) 2002 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Julian Coleman.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd October 17, 2007
.Dt CURSES_KEYNAME 3
.Os
.Sh NAME
.Nm curses_keyname ,
.Nm keyname
.Nd curses report key name routine
.Sh LIBRARY
.Lb libcurses
.Sh SYNOPSIS
.In curses.h
.Ft "char *"
.Fn keyname "int key"
.Sh DESCRIPTION
The function
.Fn keyname
generates a character string containing a description of the key specified in
.Fa key .
.Pp
The string is formatted according to the following table:
.Bl -column "Meta + control character" "KEY_MIN - KEY_MAX" "String format"
.It "Description" Ta "Key range" Ta "String format"
.It Li "Control character" Ta "0 - 31" Ta "^X"
.It Li "Visible character" Ta "32 - 126" Ta "X"
.It Li "Delete character" Ta "127" Ta "^?"
.It Li "Meta + control character" Ta "128 - 158" Ta "M-^X"
.It Li "Meta + visible character" Ta "159 - 254" Ta "M-X"
.It Li "Meta + delete character" Ta "255" Ta "M-^?"
.It Li "Named key" Ta "KEY_MIN - KEY_MAX" Ta "KEY_EXIT"
.It Li "Unknown key" Ta "" Ta "-1"
.El
.Sh SEE ALSO
.Xr curses_input 3
.Sh NOTE
The return value of
.Fn keyname
is a static buffer, which will be overwritten on a subsequent call.
.Sh STANDARDS
The
.Nx
Curses library complies with the X/Open Curses specification, part of the
Single Unix Specification.
.Sh HISTORY
These functions first appeared in
.Nx 2.0 .
