# $NetBSD: Makefile.dhcpcd,v 1.2 2014/09/12 20:42:13 roy Exp $

IMAGEDEPENDS+= 	\
	${DESTDIR}/etc/dhcpcd.conf \
	${DESTDIR}/libexec/dhcpcd-run-hooks \
	${DESTDIR}/libexec/dhcpcd-hooks/20-resolv.conf \
	${DESTDIR}/libexec/dhcpcd-hooks/30-hostname

LISTS+=		${DISTRIBDIR}/common/list.dhcpcd
