#!/bin/sh
#	$NetBSD: mkprotocols,v 1.1 2008/05/01 22:01:16 garbled Exp $
# Generate a shaved down protocols file for install media.
#
echo "#	\$NetBSD\$" > protocols
echo "# Shaved down /etc/protocols for installation media" >> protocols
/usr/bin/sed -e 's/#.*//' -e '/^$/d' -e 's/ *$//' -e 's/  */ /' ../../etc/protocols >> protocols
