# $NetBSD: Makefile.sys,v 1.3 2015/05/18 17:49:16 pooka Exp $

SYS_MKSYSCALLS=${.CURDIR}/../../../../kern/makesyscalls.sh

SYS_DST=  ${SYS_P}calls.c ${SYS_P}ent.c ${SYS_P}callargs.h ${SYS_P}call.h
SYS_SRC=${SYS_MKSYSCALLS} ${.CURDIR}/syscalls.conf ${.CURDIR}/syscalls.master

${SYS_P}callargs.h: ${SYS_SRC}
	cd ${.OBJDIR} && ${HOST_SH} ${.ALLSRC}

${SYS_P}ent.c: ${SYS_P}callargs.h

CPPFLAGS+= -I${.OBJDIR}

DPSRCS+= ${SYS_P}callargs.h
SRCS+= ${SYS_P}ent.c

CLEANFILES+= ${SYS_DST}
