#	$NetBSD: Makefile,v 1.10 2008/09/26 18:56:43 apb Exp $
#	@(#)Makefile	8.1 (Berkeley) 5/31/93

PROG=	strfile
MAN=	strfile.8
MLINKS=	strfile.8 unstr.8

.include "../../Makefile.inc"
.include <bsd.prog.mk>
