/*****************************************************************************
 * %A%
 *****************************************************************************/

/*****************************************************************************/
/** @file common/include_public/n8_pub_enums.h
 *  @brief Generated file for converting enum values to text.
 *
 * This file generated by genEnumText.py.  Do not edit by hand.
 *
 *****************************************************************************/

/*****************************************************************************
 * Revision history:
 * 03/02/04 ---   Generated.
 ****************************************************************************/

#ifndef N8_PUB_ENUMS_H
#define N8_PUB_ENUMS_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "n8_pub_hash.h" 
#include "n8_pub_packet.h" 
#include "n8_pub_service.h" 
#include "n8_pub_common.h" 
#include "n8_pub_errors.h" 

const char * N8_Hardware_t_text(const N8_Hardware_t enumValue);
const char * N8_QueueStatusCodes_t_text(const N8_QueueStatusCodes_t enumValue);
const char * N8_Status_t_text(const N8_Status_t enumValue);
const char * N8_HashProtocol_t_text(const N8_HashProtocol_t enumValue);
const char * N8_SKSKeyType_t_text(const N8_SKSKeyType_t enumValue);
const char * N8_Cipher_t_text(const N8_Cipher_t enumValue);
const char * N8_Component_t_text(const N8_Component_t enumValue);
const char * N8_KeyType_t_text(const N8_KeyType_t enumValue);
const char * N8_HashRole_t_text(const N8_HashRole_t enumValue);
const char * N8_Parameter_t_text(const N8_Parameter_t enumValue);
const char * N8_Boolean_t_text(const N8_Boolean_t enumValue);
const char * N8_Protocol_t_text(const N8_Protocol_t enumValue);
const char * N8_PacketMemoryMode_t_text(const N8_PacketMemoryMode_t enumValue);
const char * N8_HashAlgorithm_t_text(const N8_HashAlgorithm_t enumValue);
const char * N8_MemoryType_t_text(const N8_MemoryType_t enumValue);

#ifdef __cplusplus
}
#endif

#endif
