#	$NetBSD: Makefile,v 1.20 2009/04/14 22:15:25 lukem Exp $
#	from: @(#)Makefile	8.1 (Berkeley) 7/19/93

.include <bsd.own.mk>

USE_FORT?=yes	# network client

PROG=	rsh
SRCS=	rsh.c getport.c

.PATH:	${NETBSDSRCDIR}/usr.bin/rlogin

.include <bsd.prog.mk>
