#	$NetBSD: Makefile,v 1.8 2003/05/18 07:57:38 lukem Exp $

PROG=	yacc
SRCS=	closure.c error.c lalr.c lr0.c main.c mkpar.c output.c reader.c \
	skeleton.c symtab.c verbose.c warshall.c

.include <bsd.prog.mk>
