#	$NetBSD: Makefile,v 1.6 2014/03/13 02:04:59 pooka Exp $
#

.PATH:	${.CURDIR}/../../../../kern

LIB=	rumpnet_local

SRCS=	uipc_proto.c uipc_usrreq.c
SRCS+=	local_component.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
