#	$NetBSD: Makefile,v 1.9 2014/03/13 18:14:13 pooka Exp $
#

LIB=	rumpnet_virtif
VIRTIF=	virt

.include "${.CURDIR}/Makefile.virtif"

RUMPCOMP_USER_SRCS=	virtif_user.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
