#	$NetBSD: Makefile.virtif,v 1.4 2014/03/13 21:11:12 pooka Exp $
#

.if !defined(VIRTIF)
.error Define VIRTIF when including ${.PARSEFILE}
.endif

SRCS=	if_virt.c

VIRTIFDIR:=	${.PARSEDIR}
.PATH:		${VIRTIFDIR}

CPPFLAGS+=		 -DVIRTIF_BASE=${VIRTIF} -I${VIRTIFDIR}
RUMPCOMP_USER_CPPFLAGS+= -DVIRTIF_BASE=${VIRTIF} -I${VIRTIFDIR}
