#	$NetBSD: Makefile.inc,v 1.5 2009/07/30 20:57:16 dsl Exp $

SRCS+=	bcmp.S bcopy.S bzero.S ffs.S memcmp.S memset.S \
	strcat.S strcmp.S strcpy.S strlen.S \
	strncmp.S strncpy.S \
	swab.S
SRCS+=	memcpy.S memccpy.S memmove.S strchr.S strrchr.S
