# Makefile for lib/i386/misc.

CFLAGS	= -O -D_MINIX -D_POSIX_SOURCE

LIBRARIES = libc

libc_OBJECTS	= \
	alloca.o \
	get_bp.o \
	getprocessor.o \
	io_inb.o \
	io_inl.o \
	io_insb.o \
	io_insl.o \
	io_insw.o \
	io_intr.o \
	io_inw.o \
	io_outb.o \
	io_outl.o \
	io_outsb.o \
	io_outsl.o \
	io_outsw.o \
	io_outw.o \
	oneC_sum.o \

include ../../Makefile.inc
