#	@(#)Makefile	8.1 (Berkeley) 6/6/93
#	$NetBSD: Makefile,v 1.10 2009/04/14 22:15:20 lukem Exp $

.include <bsd.own.mk>

PROG=	fmt
SRCS=	fmt.c head.c
CPPFLAGS+=	-DFMT_PROG

.PATH: ${NETBSDSRCDIR}/usr.bin/mail

.include <bsd.prog.mk>
