# This file is not part of the regular Makefile.inc
# It is used from the LLVM build system, when compiling the passes.
#
# This files is used with gmake, so do NOT add .include "..."
#
LLVMPREFIX?=../../../../../obj_llvm.i386/Release+Asserts
