#define MY_SCHEDULING_ALGORITHM  5

#define STANDARD_SCHEDULING_ALGORITHM 1
#define PRIORITY_SCHEDULING_ALGORITHM  2
#define RR_SCHEDULING_ALGORITHM 3
#define MFQ_SCHEDULING_ALGORITHM 4
#define SJF_SCHEDULING_ALGORITHM 5