# int64 sources
.PATH: ${.CURDIR}/arch/${ARCH}/int64

SRCS+=  \
	add64.S \
	add64u.S \
	bsr64.S \
	cmp64.S \
	cv64u.S \
	cvu64.S \
	diff64.S \
	div64.c \
	div64u.S \
	ex64.S \
	make64.S \
	mul64.c \
	mul64u.S \
	sub64.S \
	sub64u.S
