#	$NetBSD: Makefile,v 1.7 2011/03/06 17:08:39 bouyer Exp $

INCSDIR= /usr/include/ufs/ufs

INCS=	dinode.h dir.h extattr.h inode.h quota.h quota1.h quota2.h \
	ufs_bswap.h ufs_extern.h ufs_wapbl.h ufsmount.h

.include <bsd.kinc.mk>
