.TH CAL 1
.SH NAME
cal \- print a calendar
.SH SYNOPSIS
\fBcal\fR [\fImonth\fR] \fIyear\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.TP 20
.B cal 3 1992
# Print March 1992
.SH DESCRIPTION
.PP
\fICal\fR prints a calendar for a month or year.  The year can be 
between 1 and 9999.  
Note that the year 91 is not a synonym for 1991, but is itself a
valid year about 19 centuries ago.  The calendar produced is the one used
by England and her colonies.  Try Sept. 1752, Feb 1900, and Feb 2000.  If
you do not understand what is going on, look up \fICalendar, Gregorian\fR in a
good encyclopedia.
