.TH DOSREAD 1
.SH NAME
dosread \- read a file from an MS-DOS diskette [IBM]
.SH SYNOPSIS
\fBdosread\fR [\fB\-a\fR] \fIdrive \fIfile\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH OPTIONS
.TP 5
.B \-a
# ASCII file
.SH EXAMPLES
.TP 20
.B dosread C g/adv >adv
# Read file \fIg/adv\fR from hard disk
.TP 20
.B dosread \-a A prog.c >x
# Read ASCII file \fIprog.c\fR from drive A
.SH DESCRIPTION
.PP
.I Dosread
reads one \s-2MS-DOS\s+2 file and writes it on standard output.
The file name must use slash, not backslash as a separator.
ASCII files have the final CTRL-Z stripped, and carriage return plus
line feed are mapped to line feed only, the usual
\s-1MINIX 3\s-1
convention.  See \fBdosdir\fR on the use of single letter drive codes.
