.TH DUMPCORE 1
.SH NAME
dumpcore \- generate core file of running process
.SH SYNOPSIS
dumpcore \fIpid\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH DESCRIPTION
The \fBdumpcore\fR utility generates a core file for a running process, based
on that process's process ID (\fIpid\fP). The resulting core file will be
stored under the name "core" in the current working directory. Any previous
file with that name will be overwritten.
.PP
The resulting core file can be used with for example
.BR mdb (1).
.SH BUGS
The process of generating the core file is currently very rudimentary, and
the generated core file does not contain for example memory mapped areas.
.SH "SEE ALSO"
.BR mdb (1).
