.TH EASYPACK 1
.SH NAME
easypack \- Fetch and install a package
.SH SYNOPSIS
\fBeasypack\fR [\fB\-\fIo\fR]
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH OPTIONS
.FL "\-\fIo\fR" "If package is already installed, overwrite it
.SH EXAMPLES
.EX "easypack gzip-1.2.4" "Fetch gzip-1.2.4 package"
.EX "easypack -o  indent telnet" "Refetch these 2 packages"
.SH DESCRIPTION
.PP
MINIX 3 user programs, such as emacs, kermit, and telnet are
organized into packages. The complete list is avail\%able at
\fIwww.minix3.org/software\fR. While most packages are included
on the downloadable CD-ROM image, the larger ones are not.
Any package can be easily downloaded and installed by just
giving one simple easypack command listing the package names
taken from the Website.
Each package is a .tar.bz2 file that is fetched from \fIwww.minix3.org\fR,
and then copied to \fI/usr/src/commands\fR, decompressed and untarred.
Then the \fIbuild\fR script in the top-level directory is executed
to install it. This command should be called when logged in as bin
to provide write access to the relevant directories. A log file,
\fILog\fR, is produced for debugging in case building fails.

