.TH ELVIS 1
.SH NAME
elvis, ex, vi \- The editor
.SH SYNOPSIS
\fBelvis\fP [\fIflags\fP] [\fB+\fP\fIcmd\fP] [\fIfiles\fP...]
.SH DESCRIPTION
\fBElvis\fP is a text editor which emulates \fBvi\fP/\fBex\fP.
.PP
On systems which pass the program name as an argument, such as UNIX and MINIX 3,
you may also install \fBelvis\fP under the names "ex", "vi", "view", and "input".
These extra names would normally be links to elvis;
see the "ln" shell command.
.PP
When \fBelvis\fP is invoked as "vi",
it behaves exactly as though it was invoked as "elvis".
However, if you invoke \fBelvis\fP as "view",
then the readonly option is set as though you had given it the "-R" flag.
If you invoke \fBelvis\fP as "ex",
then \fBelvis\fP will start up in the colon command mode
instead of the visual command mode,
as though you had given it the "-e" flag.
If you invoke \fBelvis\fP as "input" or "edit",
then \fBelvis\fP will start up in input mode,
as though the "-i" flag was given.
.SH OPTIONS
.IP \fB-r\fP
To the real vi, this flag means that a previous edit should be recovered.
\fBElvis\fP, though, has a separate program, called \fIelvrec\fP(1), for recovering
files.
When you invoke \fBelvis\fP with -r, \fBelvis\fP will tell you to run \fBelvrec\fP.
.IP \fB-R\fP
This sets the "readonly" option,
so you won't accidentally overwrite a file.
.IP "\fB-t\fP \fItag\fP"
This causes \fBelvis\fP to start editing at the given tag.
.IP "\fB-m\fP [\fIfile\fP]"
\fBElvis\fP will search through \fIfile\fP for something that looks like
an error message from a compiler.
It will then begin editing the source file that caused the error,
with the cursor sitting on the line where the error was detected.
If you don't explicitly name a \fIfile\fP, then "errlist" is assumed.
.IP \fB-e\fP
\fBElvis\fP will start up in colon command mode.
.IP \fB-v\fP
\fBElvis\fP will start up in visual command mode.
.IP \fB-i\fP
\fBElvis\fP will start up in input mode.
.IP "\fB-w\fR \fIwinsize\fR"
Sets the "window" option's value to \fIwinsize\fR.
.IP "\fB+\fP\fIcommand\fP or \fB-c\fP \fIcommand\fP"
If you use the +\fIcommand\fP parameter,
then after the first file is loaded
\fIcommand\fP is executed as an EX command.
A typical example would be "elvis +237 foo",
which would cause \fBelvis\fP to start editing foo and
then move directly to line 237.
The "-c \fIcommand\fP" variant was added for UNIX SysV compatibility.
.SH FILES
.IP /tmp/elv*
During editing,
\fBelvis\fP stores text in a temporary file.
For UNIX, this file will usually be stored in the /tmp directory,
and the first three characters will be "elv".
For other systems, the temporary files may be stored someplace else;
see the version-specific section of the documentation.
.IP tags
This is the database used by the \fB:tags\fP command and the \fB-t\fP option.
It is usually created by the \fBctags\fP(1) program.
.IP ".exrc or elvis.rc"
On UNIX-like systems, a file called ".exrc" in your home directory
is executed as a series of \fBex\fR commands.
A file by the same name may be executed in the current directory, too.
On non-UNIX systems, ".exrc" is usually an invalid file name;
there, the initialization file is called "elvis.rc" instead.
.SH "SEE ALSO"
.BR ctags (1),
.BR ref (1),
.BR elvrec (1),
.BR elvis (9).
.PP
\fIElvis - A Clone of Vi/Ex\fP, the complete \fBelvis\fP documentation.
.SH BUGS
There is no LISP support.
Certain other features are missing, too.
.PP
Auto-indent mode is not quite compatible with the real vi.
Among other things, 0^D and ^^D don't do what you might expect.
.PP
Long lines are displayed differently.
The real vi wraps long lines onto multiple rows of the screen,
but \fBelvis\fP scrolls sideways.
.SH AUTHOR
.nf
Steve Kirkendall
kirkenda@cs.pdx.edu
.fi
.PP
Many other people have worked to port \fBelvis\fP to various operating systems.
To see who deserves credit, run the \fB:version\fP command from within \fBelvis\fP,
or look in the system-specific section of the complete documentation.
.\" ref to virec chnaged to elvrec -- ASW 2004-12-13
