.TH FACTOR 1
.SH NAME
factor \- factor an integer less than 2**31
.SH SYNOPSIS
\fBfactor \fInumber\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.EX "factor 450180" "Print the prime factors of 450180"
.SH DESCRIPTION
.PP
\fIFactor\fR prints the prime factors of its argument in increasing order.
Each factor is printed as many times as it appears in the number.
