.TH FORTUNE 1
.SH NAME
fortune \- print a fortune
.SH SYNOPSIS
\fBfortune\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.EX "fortune" "Print a fortune"
.SH DESCRIPTION
.PP
\fIFortune\fR prints a fortune at random from the fortunes file,  
\fI/usr/lib/fortune.dat\fR.  This file consists of pieces
of text separated by a line containing only %%.
