MAN=	ash.1 at.1 basename.1 \
	bsfilt.1 cawf.1 chgrp.1 \
	chmod.1 cmp.1 comm.1 compress.1 \
	cp.1 crc.1 crontab.1 dd.1 \
	df.1 dhrystone.1 dosdir.1 dosread.1 doswrite.1 \
	dumpcore.1 eject.1 \
	env.1 expand.1 factor.1 \
	finger.1 flexdoc.1 fold.1 format.1 fortune.1 \
	fsck.mfs.1 host.1 hostaddr.1 ifdef.1 \
	isodir.1 isoinfo.1 isoread.1 \
	last.1 loadfont.1 loadkeys.1 logger.1 \
	look.1 lp.1 lspci.1 mail.1  \
	mesg.1 mixer.1 \
	mkproto.1 mount.1 mt.1 nice.1 nm.1 nohup.1 od.1 \
	paste.1 ping.1 playwave.1 pr.1 prep.1 \
	profile.1 ps.1 rcp.1 recwave.1 \
	remsync.1 rget.1 rlogin.1 rsh.1 rz.1 \
	shar.1 acksize.1 sleep.1 spell.1 \
	split.1 stty.1 svc.1 svrctl.1 \
	synctree.1 sysenv.1 sz.1 tail.1 tee.1 telnet.1 template.1 \
	term.1 termcap.1 tget.1 time.1 tr.1 true.1 \
	truncate.1 tty.1 umount.1 uname.1 unexpand.1 \
	uud.1 uue.1 vol.1 wc.1 whereis.1 which.1 \
	write.1 xargs.1 yap.1 linkfarm.1 pkg_view.1

MLINKS += ash.1 sh.1
MLINKS += ash.1 ..1
MLINKS += ash.1 break.1
MLINKS += ash.1 case.1
MLINKS += ash.1 cd.1
MLINKS += ash.1 command.1
MLINKS += ash.1 continue.1
MLINKS += ash.1 eval.1
MLINKS += ash.1 exec.1
MLINKS += ash.1 exit.1
MLINKS += ash.1 export.1
MLINKS += ash.1 for.1
MLINKS += ash.1 getopts.1
MLINKS += ash.1 hash.1
MLINKS += ash.1 if.1
MLINKS += ash.1 jobs.1
MLINKS += ash.1 local.1
MLINKS += ash.1 read.1
MLINKS += ash.1 readonly.1
MLINKS += ash.1 return.1
MLINKS += ash.1 set.1
MLINKS += ash.1 setvar.1
MLINKS += ash.1 shift.1
MLINKS += ash.1 trap.1
MLINKS += ash.1 umask.1
MLINKS += ash.1 unset.1
MLINKS += ash.1 wait.1
MLINKS += compress.1 uncompress.1
MLINKS += cp.1 mv.1
MLINKS += cp.1 cpdir.1
MLINKS += svc.1 ci.1
MLINKS += svc.1 co.1

.include <bsd.man.mk>
.include <bsd.subdir.mk>
