MAN=	acd.1 anm.1 ar.1 ash.1 asize.1 at.1 banner.1 basename.1 \
	bsfilt.1 cal.1 \
	calendar.1 cat.1 cawf.1 cc.1  chgrp.1 \
	chmem.1 chmod.1 cksum.1 clear.1 cmp.1 comm.1 compress.1 \
	cp.1 crc.1 crontab.1 ctags.1 dd.1 dev2name.1 \
	df.1 dhrystone.1 dosdir.1 dosread.1 doswrite.1 du.1 \
	dumpcore.1 echo.1 ed.1 eject.1 elvis.1 elvrec.1 \
	env.1 expand.1 expr.1 factor.1 file.1 \
	finger.1 flexdoc.1 fmt.1 fold.1 format.1 fortune.1 \
	fsck.1 head.1 host.1 hostaddr.1 ifdef.1 \
	install.1 isodir.1 isoinfo.1 isoread.1 join.1 kill.1 \
	last.1 leave.1 loadfont.1 loadkeys.1 logger.1 login.1 \
	look.1 lp.1 ls.1 lspci.1 M.1 mail.1  \
	mesg.1 mixer.1 mkdep.1 mkdir.1 mkfifo.1 mkfs.1 \
	mkproto.1 modem.1 mount.1 mt.1 nice.1 nm.1 nohup.1 od.1 \
	ossinfo.1 ossmix.1 ossplay.1 ossrecord.1 osstest.1 passwd.1 \
	paste.1 ping.1 playwave.1 postmort.1 pr.1 prep.1 \
	profile.1 ps.1 pwd.1 rcp.1 readall.1 readfs.1 recwave.1 \
	ref.1 remsync.1 rget.1 rlogin.1 rmdir.1 rsh.1 rz.1 \
	shar.1 size.1 sleep.1 sort.1 soundoff.1 soundon.1 spell.1 \
	split.1 stat.1 strings.1 strip.1 stty.1 su.1 sum.1 svc.1 \
	synctree.1 sysenv.1 sz.1 tail.1 tee.1 telnet.1 template.1 \
	term.1 termcap.1 tget.1 time.1 top.1 tr.1 true.1 \
	truncate.1 tsort.1 tty.1 umount.1 uname.1 unexpand.1 uniq.1 \
	urlget.1 uud.1 uue.1 vol.1 wc.1 whereis.1 which.1 \
	who.1 write.1 xargs.1 yap.1 yes.1 linkfarm.1 pkg_view.1


.include <bsd.man.mk>
.include <bsd.subdir.mk>
