.TH PWD 1
.SH NAME
pwd \- print working directory
.SH SYNOPSIS
\fBpwd\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.EX "pwd     " "Print the name of the working directory"
.SH DESCRIPTION
.PP
The full path name of the current working directory is printed.
.SH "SEE ALSO"
.BR getcwd (3).
