.TH SLEEP 1
.SH NAME
sleep \- suspend execution for a given number of seconds
.SH SYNOPSIS
\fBsleep \fIseconds\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.TP 20
.B sleep 10
# Suspend execution for 10 sec.
.SH DESCRIPTION
.PP
The caller is suspended for the indicated number of seconds.
This command is typically used in shell scripts.
.SH "SEE ALSO"
.BR sleep (3).
