.TH TRUE 1
.SH NAME
true, false \- exit with the value true or false
.SH SYNOPSIS
\fBtrue\fR
.br
\fBfalse\fR
.SH EXAMPLES
.ta +20n
.ft B
.nf
while true	\fR# List the directory until DEL is hit\fP
do ls \-l
done
.fi
.ft P
.SH DESCRIPTION
These commands return the value
.I true
or
.I false .
They are used for shell programming.
.SH "SEE ALSO"
.BR sh (1).
