.TH WC 1
.SH NAME
wc \- count characters, words, and lines in a file
.SH SYNOPSIS
\fBwc\fR [\fB\-clw\fR] \fIfile\fR ...\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH OPTIONS
.FL "\-c" "Print character count"
.FL "\-l" "Print line count"
.FL "\-w" "Print word count"
.SH EXAMPLES
.EX "wc file1 file2" "Print all three counts for both files"
.EX "wc \-l file" "Print line count only"
.SH DESCRIPTION
.PP
.I Wc
reads each argument and computes the number of characters, words and lines
it contains.
A word is delimited by white space (space, tab, or line feed).
If no flags are present, all three counts are printed.
