#	$NetBSD: Makefile,v 1.4 2006/12/27 12:10:09 yamt Exp $

INCSDIR= /usr/include/nfs

INCS=	krpc.h nfs.h nfsdiskless.h nfsm_subs.h nfsmount.h nfsnode.h \
	nfsproto.h nfsrtt.h nfsrvcache.h rpcv2.h xdr_subs.h

.include <bsd.kinc.mk>
