
Welcome to MINIX 3.1.8.

The system is now running and many commands work normally.  To use MINIX
in a serious way, you need to install it to your hard disk, which you
can do by typing 'setup' while logged in as root.  Then just follow the
on-screen directions.

After setup is complete, type 'shutdown' and when the boot monitor
starts, boot your new system by following the instructions at the end
of setup.
