.\"	$NetBSD: rump.halt.1,v 1.2 2010/12/12 17:15:16 pooka Exp $
.\"
.\" Copyright (c) 1990, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)reboot.8	8.1 (Berkeley) 6/9/93
.\"
.Dd December 12, 2010
.Dt RUMP.HALT 1
.Os
.Sh NAME
.Nm rump.halt
.Nd halt a rump kernel
.Sh SYNOPSIS
.Nm
.Op Fl dhn
.Sh DESCRIPTION
The
.Nm
utility exits a rump kernel.
The file system cache, if present, is flushed.
Since a rump kernel does not control its clients, they are not
directly affected by
.Nm .
However, they will be unable to request further services from the
halted rump kernel.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d
Create a core dump.
The core file is saved according to standard userland program
coredump rules, and can be later examined with a debugger.
.It Fl h
By default the process hosting the rump kernel exits.
Using this option shuts down rump kernel activity, but does not
cause the hosting process to exit.
.It Fl n
Do not flush the file system cache.
This option should be used with extreme caution.
It can be used if a virtual disk or a virtual processor is virtually on fire.
.El
.Sh SEE ALSO
.Xr rump 3
.Sh HISTORY
The
.Nm
command appeared in
.Nx 6.0 .
.Sh CAVEATS
While using
.Fl h
makes it impossible to issue further system calls, it does not necessarily
stop all activity in a rump kernel.
It is recommended this option is used only for debugging purposes.
