/* .H Function Index Definition file, generated by ELLEC */
/* FN_ defines Function Numbers (indices) for all known functions */
/* FX_ defines Function eXistence in this ELLE configuration */
#define FN_INSSELF          1 /* Insert Self */
#define FX_INSSELF          1
#define FN_QUOTINS          2 /* Quoted Insert */
#define FX_QUOTINS          2
#define FN_CRLF             3 /* CRLF */
#define FX_CRLF             3
#define FN_FCHAR            4 /* Forward Character */
#define FX_FCHAR            4
#define FN_BCHAR            5 /* Backward Character */
#define FX_BCHAR            5
#define FN_DCHAR            6 /* Delete Character */
#define FX_DCHAR            6
#define FN_BDCHAR           7 /* Backward Delete Character */
#define FX_BDCHAR           7
#define FN_DELSPC           8 /* Delete Horizontal Space */
#define FX_DELSPC           8
#define FN_TCHARS           9 /* Transpose Characters */
#define FX_TCHARS           9
#define FN_FWORD           10 /* Forward Word */
#define FX_FWORD           10
#define FN_BWORD           11 /* Backward Word */
#define FX_BWORD           11
#define FN_KWORD           12 /* Kill Word */
#define FX_KWORD           12
#define FN_BKWORD          13 /* Backward Kill Word */
#define FX_BKWORD          13
#define FN_TWORDS          14 /* Transpose Words */
#define FX_TWORDS          14
#define FN_UCWORD          15 /* Uppercase Word */
#define FX_UCWORD          15
#define FN_LCWORD          16 /* Lowercase Word */
#define FX_LCWORD          16
#define FN_UCIWORD         17 /* Uppercase Initial */
#define FX_UCIWORD         17
#define FN_BEGLINE         20 /* Beginning of Line */
#define FX_BEGLINE         20
#define FN_ENDLINE         21 /* End of Line */
#define FX_ENDLINE         21
#define FN_NXTLINE         22 /* Next Line */
#define FX_NXTLINE         22
#define FN_PRVLINE         23 /* Previous Line */
#define FX_PRVLINE         23
#define FN_DNRLINE         24 /* Down Real Line */
#define FX_DNRLINE         24
#define FN_UPRLINE         25 /* Up Real Line */
#define FX_UPRLINE         25
#define FN_OLINE           26 /* Open Line */
#define FX_OLINE           26
#define FN_DELBLINES       27 /* Delete Blank Lines */
#define FX_DELBLINES       27
#define FN_KLINE           28 /* Kill Line */
#define FX_KLINE           28
#define FN_BKLINE          29 /* Backward Kill Line */
#define FX_BKLINE          29
#define FN_GOLINE          30 /* Goto Line */
#define FX_GOLINE          30
#define FN_SETMARK         35 /* Set/Pop Mark */
#define FX_SETMARK         35
#define FN_EXCHMARK        36 /* Exchange Point and Mark */
#define FX_EXCHMARK        36
#define FN_KREGION         37 /* Kill Region */
#define FX_KREGION         37
#define FN_COPREG          38 /* Copy Region */
#define FX_COPREG          38
#define FN_UCREG           39 /* Uppercase Region */
#define FX_UCREG           39
#define FN_LCREG           40 /* Lowercase Region */
#define FX_LCREG           40
#define FN_FILLREG         41 /* Fill Region */
#define FX_FILLREG         41
#define FN_FPARA           45 /* Forward Paragraph */
#define FX_FPARA           45
#define FN_BPARA           46 /* Backward Paragraph */
#define FX_BPARA           46
#define FN_MRKPARA         47 /* Mark Paragraph */
#define FX_MRKPARA         47
#define FN_FILLPARA        48 /* Fill Paragraph */
#define FX_FILLPARA        48
#define FN_SELBUFFER       50 /* Select Buffer */
#define FX_SELBUFFER       50
#define FN_SELXBUFFER      51 /* Select Existing Buffer */
#define FX_SELXBUFFER      51
#define FN_KBUFFER         52 /* Kill Buffer */
#define FX_KBUFFER         52
#define FN_LISTBUFS        53 /* List Buffers */
#define FX_LISTBUFS        53
#define FN_BUFNOTMOD       54 /* Buffer Not Modified */
#define FX_BUFNOTMOD       54
#define FN_EOLMODE         55 /* EOL CRLF Mode */
#define FX_EOLMODE         55
#define FN_GOBEG           56 /* Goto Beginning */
#define FX_GOBEG           56
#define FN_GOEND           57 /* Goto End */
#define FX_GOEND           57
#define FN_WHATPAGE        58 /* What Page */
#define FX_WHATPAGE        58
#define FN_FFILE           60 /* Find File */
#define FX_FFILE           60
#define FN_RFILE           61 /* Read File */
#define FX_RFILE           61
#define FN_VFILE           62 /* Visit File */
#define FX_VFILE           62
#define FN_IFILE           63 /* Insert File */
#define FX_IFILE           63
#define FN_SFILE           64 /* Save File */
#define FX_SFILE           64
#define FN_SAVEFILES       65 /* Save All Files */
#define FX_SAVEFILES       65
#define FN_WFILE           66 /* Write File */
#define FX_WFILE           66
#define FN_WREG            67 /* Write Region */
#define FX_WREG            67
#define FN_WLASTKILL       68 /* Write Last Kill */
#define FX_WLASTKILL       68
#define FN_2WINDS          70 /* Two Windows */
#define FX_2WINDS          70
#define FN_1WIND           71 /* One Window */
#define FX_1WIND           71
#define FN_OTHWIND         72 /* Other Window */
#define FX_OTHWIND         72
#define FN_GROWIND         73 /* Grow Window */
#define FX_GROWIND         73
#define FN_SHRINKWIND      74 /* Shrink Window */
#define FX_SHRINKWIND      74
#define FN_DELWIND         75 /* Delete Window */
#define FX_DELWIND         75
#define FN_SOWIND          76 /* Standout Window */
#define FX_SOWIND          76
#define FN_2MODEWINDS      77 /* Two Mode Windows */
#define FX_2MODEWINDS      77
#define FN_NEWWIN          78 /* New Window */
#define FX_NEWWIN          78
#define FN_NSCREEN         79 /* Next Screen */
#define FX_NSCREEN         79
#define FN_PSCREEN         80 /* Previous Screen */
#define FX_PSCREEN         80
#define FN_OTHNSCREEN      81 /* Other New Screen */
#define FX_OTHNSCREEN       0
#define FN_LWINDBORD       82 /* Line to Window Border */
#define FX_LWINDBORD        0
#define FN_SCUPWIND        83 /* Scroll Window Up */
#define FX_SCUPWIND        83
#define FN_SCDNWIND        84 /* Scroll Window Down */
#define FX_SCDNWIND        84
#define FN_MVWTOP          85 /* Move to Window Top */
#define FX_MVWTOP          85
#define FN_MVWBOT          86 /* Move to Window Bottom */
#define FX_MVWBOT          86
#define FN_SETPROF         90 /* Set Profile */
#define FX_SETPROF         90
#define FN_PFXMETA         91 /* Prefix Meta */
#define FX_PFXMETA         91
#define FN_PFXEXT          92 /* Prefix Extend */
#define FX_PFXEXT          92
#define FN_UARG            93 /* Universal Arg */
#define FX_UARG            93
#define FN_NEGARG          94 /* Negative Argument */
#define FX_NEGARG          94
#define FN_ARGDIG          95 /* Argument Digit */
#define FX_ARGDIG          95
#define FN_VTBUTTONS       96 /* VT100 Button Hack */
#define FX_VTBUTTONS       96
#define FN_DESCRIBE        97 /* Describe */
#define FX_DESCRIBE        97
#define FN_SKMAC          100 /* Start Kbd Macro */
#define FX_SKMAC          100
#define FN_EKMAC          101 /* End Kbd Macro */
#define FX_EKMAC          101
#define FN_XKMAC          102 /* Execute Kbd Macro */
#define FX_XKMAC          102
#define FN_VKMAC          103 /* View Kbd Macro */
#define FX_VKMAC          103
#define FN_UNKILL         105 /* Un-kill */
#define FX_UNKILL         105
#define FN_UNKPOP         106 /* Un-kill Pop */
#define FX_UNKPOP         106
#define FN_APPNKILL       107 /* Append Next Kill */
#define FX_APPNKILL       107
#define FN_SRCH           110 /* String Search */
#define FX_SRCH           110
#define FN_RSRCH          111 /* Reverse String Search */
#define FX_RSRCH          111
#define FN_ISRCH          112 /* Incremental Search */
#define FX_ISRCH          112
#define FN_RISRCH         113 /* Reverse Search */
#define FX_RISRCH         113
#define FN_REPSTR         114 /* Replace String */
#define FX_REPSTR         114
#define FN_QUEREP         115 /* Query Replace */
#define FX_QUEREP         115
#define FN_REPLINE        116 /* Replace in Line */
#define FX_REPLINE        116
#define FN_SFCOL          117 /* Set Fill Column */
#define FX_SFCOL          117
#define FN_SFPREF         118 /* Set Fill Prefix */
#define FX_SFPREF         118
#define FN_FILLMODE       119 /* Auto Fill Mode */
#define FX_FILLMODE       119
#define FN_TEXTMODE       120 /* Text Mode */
#define FX_TEXTMODE         0
#define FN_INDATM         121 /* Indent According to Mode */
#define FX_INDATM         121
#define FN_INDNL          122 /* Indent New Line */
#define FX_INDNL          122
#define FN_BACKIND        123 /* Back to Indentation */
#define FX_BACKIND        123
#define FN_INDCOMM        124 /* Indent for Comment */
#define FX_INDCOMM        124
#define FN_INDREL         125 /* Indent Relative */
#define FX_INDREL         125
#define FN_MATCHBRACK     129 /* Match Bracket */
#define FX_MATCHBRACK       0
#define FN_PSHINF         130 /* Push to Inferior */
#define FX_PSHINF         130
#define FN_RETSUP         131 /* Return to Superior */
#define FX_RETSUP         131
#define FN_WFEXIT         132 /* Write File Exit */
#define FX_WFEXIT         132
#define FN_BKPT           140 /* Hit Breakpoint */
#define FX_BKPT           140
#define FN_DEBUG          141 /* Debug Mode */
#define FX_DEBUG          141
#define FN_XUCMD          150 /* Execute Unix Command */
#define FX_XUCMD            0
#define FN_MAKE           151 /* Execute Make */
#define FX_MAKE             0
#define FN_NXTERR         152 /* Find Next Error */
#define FX_NXTERR           0
#define FN_ICOXCMD        153 /* ICO Extend Command */
#define FX_ICOXCMD          0
#define FN_ICOTYPFNS      154 /* ICO Typeset Funs */
#define FX_ICOTYPFNS        0
#define FN_ICOSPIFNS      155 /* ICO Spec Input Funs */
#define FX_ICOSPIFNS        0
#define FN_STUFFSEL       156 /* Stuff Selection */
#define FX_STUFFSEL         0
#define FN_SELREGION      157 /* Select Region */
#define FX_SELREGION        0
