#!/bin/sh

make >/dev/null

echo -n "Kernel test (sys_vumap): "
minix-service up `pwd`/vumaprelay -config system.conf -label vumaprelay -script /etc/rs.single
minix-service up `pwd`/vumaptest -config system.conf -script /etc/rs.single 2>/dev/null
r=$?
minix-service down vumaprelay

if [ $r -ne 0 ]; then
  echo "failure"
  exit 1
fi

echo "ok"
