Global:delete FROM_CMDLINE (not found)
Command:FROM_CMDLINE = 
Global:.MAKEOVERRIDES =  FROM_CMDLINE
Global:VAR = added
Global:VAR = overwritten
Global:delete VAR
Global:delete VAR (not found)
Var_Parse: ${:U} (eval)
Applying ${:U} to "" (eval, none, undefined)
Result of ${:U} is "" (eval, none, defined)
Var_Set("${:U}", "empty name", ...) name expands to empty string - ignored
Var_Parse: ${:U} (eval)
Applying ${:U} to "" (eval, none, undefined)
Result of ${:U} is "" (eval, none, defined)
Var_Append("${:U}", "empty name", ...) name expands to empty string - ignored
Global:FROM_CMDLINE = overwritten ignored!
Global:VAR = 1
Global:VAR = 1 2
Global:VAR = 1 2 3
Var_Parse: ${VAR:M[2]} (eval-defined)
Applying ${VAR:M...} to "1 2 3" (eval-defined, none, regular)
Pattern[VAR] for [1 2 3] is [[2]]
ModifyWords: split "1 2 3" into 3 words
VarMatch [1] [[2]]
VarMatch [2] [[2]]
VarMatch [3] [[2]]
Result of ${VAR:M[2]} is "2" (eval-defined, none, regular)
Var_Parse: ${VAR:N[2]} (eval-defined)
Applying ${VAR:N...} to "1 2 3" (eval-defined, none, regular)
Pattern[VAR] for [1 2 3] is [[2]]
ModifyWords: split "1 2 3" into 3 words
Result of ${VAR:N[2]} is "1 3" (eval-defined, none, regular)
Var_Parse: ${VAR:S,2,two,} (eval-defined)
Applying ${VAR:S...} to "1 2 3" (eval-defined, none, regular)
Modifier part: "2"
Modifier part: "two"
ModifyWords: split "1 2 3" into 3 words
Result of ${VAR:S,2,two,} is "1 two 3" (eval-defined, none, regular)
Var_Parse: ${VAR:Q} (eval-defined)
Applying ${VAR:Q} to "1 2 3" (eval-defined, none, regular)
Result of ${VAR:Q} is "1\ 2\ 3" (eval-defined, none, regular)
Var_Parse: ${VAR:tu:tl:Q} (eval-defined)
Applying ${VAR:t...} to "1 2 3" (eval-defined, none, regular)
Result of ${VAR:tu} is "1 2 3" (eval-defined, none, regular)
Applying ${VAR:t...} to "1 2 3" (eval-defined, none, regular)
Result of ${VAR:tl} is "1 2 3" (eval-defined, none, regular)
Applying ${VAR:Q} to "1 2 3" (eval-defined, none, regular)
Result of ${VAR:Q} is "1\ 2\ 3" (eval-defined, none, regular)
Var_Parse: ${:Uvalue:${:UM*e}:Mvalu[e]} (eval-defined)
Applying ${:U...} to "" (eval-defined, none, undefined)
Result of ${:Uvalue} is "value" (eval-defined, none, defined)
Var_Parse: ${:UM*e}:Mvalu[e]} (eval-defined)
Applying ${:U...} to "" (eval-defined, none, undefined)
Result of ${:UM*e} is "M*e" (eval-defined, none, defined)
Indirect modifier "M*e" from "${:UM*e}"
Applying ${:M...} to "value" (eval-defined, none, defined)
Pattern[] for [value] is [*e]
ModifyWords: split "value" into 1 words
VarMatch [value] [*e]
Result of ${:M*e} is "value" (eval-defined, none, defined)
Applying ${:M...} to "value" (eval-defined, none, defined)
Pattern[] for [value] is [valu[e]]
ModifyWords: split "value" into 1 words
VarMatch [value] [valu[e]]
Result of ${:Mvalu[e]} is "value" (eval-defined, none, defined)
Var_Parse: ${:UVAR} (eval)
Applying ${:U...} to "" (eval, none, undefined)
Result of ${:UVAR} is "VAR" (eval, none, defined)
Global:delete VAR
Var_Parse: ${:Uvariable:unknown} (eval-defined)
Applying ${:U...} to "" (eval-defined, none, undefined)
Result of ${:Uvariable} is "variable" (eval-defined, none, defined)
Applying ${:u...} to "variable" (eval-defined, none, defined)
make: "vardebug.mk" line 44: Unknown modifier "unknown"
Result of ${:unknown} is error (eval-defined, none, defined)
make: "vardebug.mk" line 44: Malformed conditional (${:Uvariable:unknown})
Var_Parse: ${UNDEFINED} (eval-defined)
make: "vardebug.mk" line 53: Malformed conditional (${UNDEFINED})
Global:delete .SHELL (not found)
Command:.SHELL = </path/to/shell>
Command:.SHELL = overwritten ignored (read-only)
Global:.MAKEFLAGS =  -r -k -d v -d
Global:.MAKEFLAGS =  -r -k -d v -d 0
make: Fatal errors encountered -- cannot continue
make: stopped in unit-tests
exit status 1
