# string sources
.PATH: ${.CURDIR}/arch/${ARCH}/string

SRCS+=  \
	_memmove.S \
	_strncat.S \
	_strncmp.S \
	_strncpy.S \
	_strnlen.S \
	bcmp.S \
	bcopy.S \
	bzero.S \
	index.S \
	memchr.S \
	memcmp.S \
	memcpy.S \
	memmove.S \
	memset.S \
	rindex.S \
	strcat.S \
	strchr.S \
	strcmp.S \
	strcpy.S \
	strlen.S \
	strncat.S \
	strncmp.S \
	strncpy.S \
	strnlen.S \
	strrchr.S
