# string sources
.PATH: ${.CURDIR}/arch/${ARCH}/string

SRCS+=  \
	_memmove.s \
	_strncat.s \
	_strncmp.s \
	_strncpy.s \
	_strnlen.s \
	bcmp.s \
	bcopy.s \
	bzero.s \
	index.s \
	memchr.s \
	memcmp.s \
	memcpy.s \
	memmove.s \
	memset.s \
	rindex.s \
	strcat.s \
	strchr.s \
	strcmp.s \
	strcpy.s \
	strlen.s \
	strncat.s \
	strncmp.s \
	strncpy.s \
	strnlen.s \
	strrchr.s
