.\"	$NetBSD: form_field.3,v 1.12 2012/10/08 18:15:09 njoly Exp $
.\"
.\" Copyright (c) 2001
.\"	Brett Lymn - blymn@baea.com.au, brett_lymn@yahoo.com.au
.\"
.\" This code is donated to The NetBSD Foundation by the author.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. The name of the Author may not be used to endorse or promote
.\"    products derived from this software without specific prior written
.\"    permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd January 1, 2001
.Dt FORMS 3
.Os
.Sh NAME
.Nm field_count ,
.Nm form_fields ,
.Nm move_field ,
.Nm set_form_fields
.Nd form library
.Sh LIBRARY
.Lb libform
.Sh SYNOPSIS
.In form.h
.Ft int
.Fn field_count "FORM *form"
.Ft FIELD **
.Fn form_fields "FORM *form"
.Ft int
.Fn move_field "FIELD *field" "int frow" "int fcol"
.Ft int
.Fn set_form_fields "FORM *form" "FIELD **fields"
.Sh DESCRIPTION
The
.Fn field_count
function returns the number of fields that are attached to the given
form, if the form argument passed is
.Dv NULL
then
.Fn field_count
will return \-1.
The function
.Fn form_fields
will return a pointer to array of attach fields for the given form,
this array is not
.Dv NULL
terminated, fields may be attached to the given
form by calling
.Fn set_form_fields .
The
.Fa fields
argument in this function is a pointer to a
.Dv NULL
terminated array of
fields that will be attached to the form.
If there are already fields attached to the form then they will be
detached before the new fields are attached.
The new fields given must not be attached to any other form.
The
.Fn move_field
function will move the given field to the location specified by
.Fa frow
and
.Fa fcol .
.Sh RETURN VALUES
Functions returning pointers will return
.Dv NULL
if an error is detected.
The functions that return an int will return one of the following error
values:
.Pp
.Bl -tag -width E_UNKNOWN_COMMAND -compact
.It Er E_OK
The function was successful.
.It Er E_CONNECTED
The field is connected to a form.
.It Er E_POSTED
The form is currently posted to the screen.
.It Er E_BAD_ARGUMENT
The function was passed a bad argument.
.El
.Sh SEE ALSO
.Xr curses 3 ,
.Xr forms 3
.Sh NOTES
The header
.In form.h
automatically includes both
.In curses.h
and
.In eti.h .
