#	$NetBSD: Makefile,v 1.1 2010/03/29 18:12:23 pooka Exp $
#

.PATH:  ${.CURDIR}/../../../../fs/union

LIB=	rumpfs_union

SRCS=	union_subr.c union_vfsops.c union_vnops.c

.include <bsd.lib.mk>
.include <bsd.klinks.mk>
