#	$NetBSD: Makefile,v 1.31 2012/09/27 18:28:56 alnsn Exp $

#LSC: radix.h and route.h are used in libsa but not installed

INCSDIR= /usr/include/net

INCS=	ethertypes.h \
	if_ether.h \
	\
	\
	\
	

#SUBDIR=	agr npf

.include <bsd.kinc.mk>

#.PATH: ${NETBSDSRCDIR}/sys/dist/pf/net
