#	$NetBSD: Makefile,v 1.8 2008/01/28 07:03:59 dholland Exp $
#	@(#)Makefile	8.1 (Berkeley) 5/31/93

PROG=	caesar
MAN=	caesar.6
DPADD=	${LIBM}
LDADD=	-lm
MLINKS=	caesar.6 rot13.6
SCRIPTS=rot13.sh

.include <bsd.prog.mk>
