.include <minix.sys.mk>

INCSDIR=        /usr/include/sys

INCS=	asynchio.h dir.h file.h fpu.h ioc_cmos.h ioc_disk.h \
	ioc_file.h ioc_memory.h ioc_scsi.h ioc_sound.h ioc_tape.h \
	ioctl.h ioc_tty.h ipc.h jmp_buf.h kbdio.h mman.h \
	mount.h mtio.h param.h ptrace.h queue.h resource.h \
	select.h sem.h shm.h sigcontext.h signal.h socket.h \
	soundcard.h stackframe.h statfs.h stat.h svrctl.h timeb.h \
	time.h times.h types.h uio.h un.h utsname.h video.h vm.h \
	wait.h

.include <minix.kinc.mk>
