.include <bsd.sys.mk>

INCSDIR=        /usr/include/sys

INCS=	asynchio.h dir.h file.h ioc_cmos.h ioc_disk.h \
	ioc_file.h ioc_memory.h ioc_scsi.h ioc_sound.h ioc_tape.h \
	ioctl.h ioc_tty.h ipc.h jmp_buf.h kbdio.h mman.h \
	mount.h mtio.h param.h ptrace.h queue.h resource.h \
	select.h sem.h shm.h sigcontext.h signal.h socket.h \
	soundcard.h statfs.h statvfs.h stat.h svrctl.h timeb.h \
	time.h times.h types.h ucontext.h ucred.h uio.h un.h \
	utsname.h video.h vm.h wait.h cdefs.h null.h poll.h

.include <bsd.kinc.mk>
